{<#rt>
'sblsh':'${serviceReport.sblsh!""}',<#rt>
'sxbm':'${serviceReport.sxbm!""}',<#rt>
'sxmc':'${serviceReport.sxmc!""}',<#rt>
'fsxbm':'${serviceReport.fsxbm!""}',<#rt>
'fsxmc':'${serviceReport.fsxmc!""}',<#rt>
'sqrlx':'${serviceReport.sqrlx!""}',<#rt>
'sqrmc':'${serviceReport.sqrmc!""}',<#rt>
'sqrzjlx':'${serviceReport.sqrzjlx!""}',<#rt>
'sqrzjhm':'${serviceReport.sqrzjhm!""}',<#rt>
'lxrxm':'${serviceReport.lxrxm!""}',<#rt>
'lxrzjlx':'${serviceReport.lxrzjlx!""}',<#rt>
'lxrsfzjhm':'${serviceReport.lxrsfzjhm!""}',<#rt>
'lxrsj':'${serviceReport.lxrsj!""}',<#rt>
'lxryx':'${serviceReport.lxryx!""}',<#rt>
'sbxmmc':'${serviceReport.sbxmmc!serviceReport.sxmc}',<#rt>
'sbclqd':'${serviceReport.sbclqd!""}',<#rt>
'tjfs':'${serviceReport.tjfs!""}',<#rt>
'sbhzh':'${serviceReport.sbhzh!""}',<#rt>
'sbsj':'${(serviceReport.sbsj?string("yyyy-MM-dd HH:mm:ss"))!""}',<#rt>
'sbjtwd':'金湾区',<#rt>
'xzqhdm':'440404',<#rt>
'ysblsh':'',<#rt>
'transactor':'${serviceReport.transactorname!""}',<#rt>
'bz':'',<#rt>
'byzd':'',<#rt>
'sqbdxq':'',<#rt>
'dlyhm':'${serviceReport.dlyhm!""}'<#rt>
}<#rt>