{<#rt>
'sblsh':'${serviceReport.sblsh!""}',<#rt>
'sxbm':'${serviceReport.sxbm!""}',<#rt>
'xh':'${serviceReport.xh!""}',<#rt>
'tbcxjg':'${serviceReport.tbcxjg!""}',<#rt>
'jgcsrq':'${serviceReport.jgcsrq!""}',<#rt>
'tbcxjsrq':'${serviceReport.tbcxjsrq!""}',<#rt>
'tbcxsfje':'${serviceReport.tbcxsfje!"0"}',<#rt>
'jedwdm':'${serviceReport.jedwdm!""}',<#rt>
'xzqhdm':'440404',<#rt>
'tbcxsort':'${serviceReport.xh!""}',
'transactor':'${serviceReport.transactorname!""}',<#rt>
'bz':'',<#rt>
'byzd':''<#rt>
}<#rt>