{<#rt>
'sblsh':'${serviceReport.sblsh!""}',<#rt>
'sxbm':'${serviceReport.sxbm!""}',<#rt>
'ywlsh':'${serviceReport.ywlsh!""}',<#rt>
'yslbmmc':'${serviceReport.yslbmmc!""}',<#rt>
'yslbmzzjgdm':'${serviceReport.yslbmzzjgdm!""}',<#rt>
'xzqhdm':'${serviceReport.xzqhdm!""}',<#rt>
'blrxm':'${serviceReport.blrxm!""}',<#rt>
'blrgh':'${serviceReport.blrgh!""}',<#rt>
'yslztdm':'1',<#rt>
'bslyy':'',<#rt>
'bjbzsm':'${serviceReport.bjbzsm!""}',<#rt>
'yslsj':'${serviceReport.yslsj!""}',<#rt>
'ysljtdd':'金湾区',<#rt>
'transactor':'${serviceReport.transactorname!""}',<#rt>
'bz':'',<#rt>
'byzd':''<#rt>
}<#rt>