package com.lpcode.modules.blsp.entity;

import java.util.Date;

public class DimHoliday {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_holiday.ID
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_holiday.YEAR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_holiday.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_holiday.CREATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_holiday.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_holiday.UPDATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_holiday.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_holiday.HOLIDAYS
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String holidays;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_holiday.ID
     *
     * @return the value of dim_holiday.ID
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_holiday.ID
     *
     * @param id the value for dim_holiday.ID
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_holiday.YEAR
     *
     * @return the value of dim_holiday.YEAR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_holiday.YEAR
     *
     * @param year the value for dim_holiday.YEAR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_holiday.CREAT_TIME
     *
     * @return the value of dim_holiday.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_holiday.CREAT_TIME
     *
     * @param creatTime the value for dim_holiday.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_holiday.CREATOR
     *
     * @return the value of dim_holiday.CREATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_holiday.CREATOR
     *
     * @param creator the value for dim_holiday.CREATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_holiday.UPDATE_TIME
     *
     * @return the value of dim_holiday.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_holiday.UPDATE_TIME
     *
     * @param updateTime the value for dim_holiday.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_holiday.UPDATOR
     *
     * @return the value of dim_holiday.UPDATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_holiday.UPDATOR
     *
     * @param updator the value for dim_holiday.UPDATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_holiday.IS_DELETE
     *
     * @return the value of dim_holiday.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_holiday.IS_DELETE
     *
     * @param isDelete the value for dim_holiday.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_holiday.HOLIDAYS
     *
     * @return the value of dim_holiday.HOLIDAYS
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getHolidays() {
        return holidays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_holiday.HOLIDAYS
     *
     * @param holidays the value for dim_holiday.HOLIDAYS
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setHolidays(String holidays) {
        this.holidays = holidays;
    }
}