package com.lpcode.modules.blsp.entity;

import java.util.Date;

public class DimPauseType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.ID
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.NAME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.DESCRIPTION
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.DURATION
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.TIME_TYPE
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String timeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.IS_VALID
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.CREATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dim_pause_type.UPDATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String updator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.ID
     *
     * @return the value of dim_pause_type.ID
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.ID
     *
     * @param id the value for dim_pause_type.ID
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.IS_DELETE
     *
     * @return the value of dim_pause_type.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.IS_DELETE
     *
     * @param isDelete the value for dim_pause_type.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.NAME
     *
     * @return the value of dim_pause_type.NAME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.NAME
     *
     * @param name the value for dim_pause_type.NAME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.DESCRIPTION
     *
     * @return the value of dim_pause_type.DESCRIPTION
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.DESCRIPTION
     *
     * @param description the value for dim_pause_type.DESCRIPTION
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.DURATION
     *
     * @return the value of dim_pause_type.DURATION
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.DURATION
     *
     * @param duration the value for dim_pause_type.DURATION
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.TIME_TYPE
     *
     * @return the value of dim_pause_type.TIME_TYPE
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getTimeType() {
        return timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.TIME_TYPE
     *
     * @param timeType the value for dim_pause_type.TIME_TYPE
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setTimeType(String timeType) {
        this.timeType = timeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.IS_VALID
     *
     * @return the value of dim_pause_type.IS_VALID
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.IS_VALID
     *
     * @param isValid the value for dim_pause_type.IS_VALID
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.CREAT_TIME
     *
     * @return the value of dim_pause_type.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.CREAT_TIME
     *
     * @param creatTime the value for dim_pause_type.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.CREATOR
     *
     * @return the value of dim_pause_type.CREATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.CREATOR
     *
     * @param creator the value for dim_pause_type.CREATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.UPDATE_TIME
     *
     * @return the value of dim_pause_type.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.UPDATE_TIME
     *
     * @param updateTime the value for dim_pause_type.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dim_pause_type.UPDATOR
     *
     * @return the value of dim_pause_type.UPDATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dim_pause_type.UPDATOR
     *
     * @param updator the value for dim_pause_type.UPDATOR
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }
}