package com.lpcode.modules.blsp.entity;

public class FormHbJsxmGyxmCp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_gyxm_cp.P_ID
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    private Long pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_gyxm_cp.H_ID
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    private Long hId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_gyxm_cp.P_IS_DELETE
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    private String pIsDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_gyxm_cp.P_NAME
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_gyxm_cp.P_YIELD
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    private String pYield;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_gyxm_cp.P_ID
     *
     * @return the value of form_hb_jsxm_gyxm_cp.P_ID
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    public Long getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_gyxm_cp.P_ID
     *
     * @param pId the value for form_hb_jsxm_gyxm_cp.P_ID
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    public void setpId(Long pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_gyxm_cp.H_ID
     *
     * @return the value of form_hb_jsxm_gyxm_cp.H_ID
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    public Long gethId() {
        return hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_gyxm_cp.H_ID
     *
     * @param hId the value for form_hb_jsxm_gyxm_cp.H_ID
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    public void sethId(Long hId) {
        this.hId = hId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_gyxm_cp.P_IS_DELETE
     *
     * @return the value of form_hb_jsxm_gyxm_cp.P_IS_DELETE
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    public String getpIsDelete() {
        return pIsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_gyxm_cp.P_IS_DELETE
     *
     * @param pIsDelete the value for form_hb_jsxm_gyxm_cp.P_IS_DELETE
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    public void setpIsDelete(String pIsDelete) {
        this.pIsDelete = pIsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_gyxm_cp.P_NAME
     *
     * @return the value of form_hb_jsxm_gyxm_cp.P_NAME
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_gyxm_cp.P_NAME
     *
     * @param pName the value for form_hb_jsxm_gyxm_cp.P_NAME
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    public void setpName(String pName) {
        this.pName = pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_gyxm_cp.P_YIELD
     *
     * @return the value of form_hb_jsxm_gyxm_cp.P_YIELD
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    public String getpYield() {
        return pYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_gyxm_cp.P_YIELD
     *
     * @param pYield the value for form_hb_jsxm_gyxm_cp.P_YIELD
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    public void setpYield(String pYield) {
        this.pYield = pYield;
    }
}