package com.lpcode.modules.blsp.entity;

import java.util.ArrayList;
import java.util.List;

public class FormGtJsydSqbJsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    protected int start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public FormGtJsydSqbJsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public void setStart(int start) {
        this.start=start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public int getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBIdIsNull() {
            addCriterion("B_ID is null");
            return (Criteria) this;
        }

        public Criteria andBIdIsNotNull() {
            addCriterion("B_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBIdEqualTo(Long value) {
            addCriterion("B_ID =", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdNotEqualTo(Long value) {
            addCriterion("B_ID <>", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdGreaterThan(Long value) {
            addCriterion("B_ID >", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdGreaterThanOrEqualTo(Long value) {
            addCriterion("B_ID >=", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdLessThan(Long value) {
            addCriterion("B_ID <", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdLessThanOrEqualTo(Long value) {
            addCriterion("B_ID <=", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdIn(List<Long> values) {
            addCriterion("B_ID in", values, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdNotIn(List<Long> values) {
            addCriterion("B_ID not in", values, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdBetween(Long value1, Long value2) {
            addCriterion("B_ID between", value1, value2, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdNotBetween(Long value1, Long value2) {
            addCriterion("B_ID not between", value1, value2, "bId");
            return (Criteria) this;
        }

        public Criteria andGIdIsNull() {
            addCriterion("G_ID is null");
            return (Criteria) this;
        }

        public Criteria andGIdIsNotNull() {
            addCriterion("G_ID is not null");
            return (Criteria) this;
        }

        public Criteria andGIdEqualTo(Long value) {
            addCriterion("G_ID =", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotEqualTo(Long value) {
            addCriterion("G_ID <>", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThan(Long value) {
            addCriterion("G_ID >", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThanOrEqualTo(Long value) {
            addCriterion("G_ID >=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThan(Long value) {
            addCriterion("G_ID <", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThanOrEqualTo(Long value) {
            addCriterion("G_ID <=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdIn(List<Long> values) {
            addCriterion("G_ID in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotIn(List<Long> values) {
            addCriterion("G_ID not in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdBetween(Long value1, Long value2) {
            addCriterion("G_ID between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotBetween(Long value1, Long value2) {
            addCriterion("G_ID not between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteIsNull() {
            addCriterion("B_IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteIsNotNull() {
            addCriterion("B_IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteEqualTo(String value) {
            addCriterion("B_IS_DELETE =", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteNotEqualTo(String value) {
            addCriterion("B_IS_DELETE <>", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteGreaterThan(String value) {
            addCriterion("B_IS_DELETE >", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteGreaterThanOrEqualTo(String value) {
            addCriterion("B_IS_DELETE >=", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteLessThan(String value) {
            addCriterion("B_IS_DELETE <", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteLessThanOrEqualTo(String value) {
            addCriterion("B_IS_DELETE <=", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteLike(String value) {
            addCriterion("B_IS_DELETE like", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteNotLike(String value) {
            addCriterion("B_IS_DELETE not like", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteIn(List<String> values) {
            addCriterion("B_IS_DELETE in", values, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteNotIn(List<String> values) {
            addCriterion("B_IS_DELETE not in", values, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteBetween(String value1, String value2) {
            addCriterion("B_IS_DELETE between", value1, value2, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteNotBetween(String value1, String value2) {
            addCriterion("B_IS_DELETE not between", value1, value2, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjIsNull() {
            addCriterion("B_BUILD_PRJ is null");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjIsNotNull() {
            addCriterion("B_BUILD_PRJ is not null");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjEqualTo(String value) {
            addCriterion("B_BUILD_PRJ =", value, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjNotEqualTo(String value) {
            addCriterion("B_BUILD_PRJ <>", value, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjGreaterThan(String value) {
            addCriterion("B_BUILD_PRJ >", value, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjGreaterThanOrEqualTo(String value) {
            addCriterion("B_BUILD_PRJ >=", value, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjLessThan(String value) {
            addCriterion("B_BUILD_PRJ <", value, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjLessThanOrEqualTo(String value) {
            addCriterion("B_BUILD_PRJ <=", value, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjLike(String value) {
            addCriterion("B_BUILD_PRJ like", value, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjNotLike(String value) {
            addCriterion("B_BUILD_PRJ not like", value, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjIn(List<String> values) {
            addCriterion("B_BUILD_PRJ in", values, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjNotIn(List<String> values) {
            addCriterion("B_BUILD_PRJ not in", values, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjBetween(String value1, String value2) {
            addCriterion("B_BUILD_PRJ between", value1, value2, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjNotBetween(String value1, String value2) {
            addCriterion("B_BUILD_PRJ not between", value1, value2, "bBuildPrj");
            return (Criteria) this;
        }

        public Criteria andBUnmIsNull() {
            addCriterion("B_UNM is null");
            return (Criteria) this;
        }

        public Criteria andBUnmIsNotNull() {
            addCriterion("B_UNM is not null");
            return (Criteria) this;
        }

        public Criteria andBUnmEqualTo(String value) {
            addCriterion("B_UNM =", value, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmNotEqualTo(String value) {
            addCriterion("B_UNM <>", value, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmGreaterThan(String value) {
            addCriterion("B_UNM >", value, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmGreaterThanOrEqualTo(String value) {
            addCriterion("B_UNM >=", value, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmLessThan(String value) {
            addCriterion("B_UNM <", value, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmLessThanOrEqualTo(String value) {
            addCriterion("B_UNM <=", value, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmLike(String value) {
            addCriterion("B_UNM like", value, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmNotLike(String value) {
            addCriterion("B_UNM not like", value, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmIn(List<String> values) {
            addCriterion("B_UNM in", values, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmNotIn(List<String> values) {
            addCriterion("B_UNM not in", values, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmBetween(String value1, String value2) {
            addCriterion("B_UNM between", value1, value2, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBUnmNotBetween(String value1, String value2) {
            addCriterion("B_UNM not between", value1, value2, "bUnm");
            return (Criteria) this;
        }

        public Criteria andBFloorsIsNull() {
            addCriterion("B_FLOORS is null");
            return (Criteria) this;
        }

        public Criteria andBFloorsIsNotNull() {
            addCriterion("B_FLOORS is not null");
            return (Criteria) this;
        }

        public Criteria andBFloorsEqualTo(String value) {
            addCriterion("B_FLOORS =", value, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsNotEqualTo(String value) {
            addCriterion("B_FLOORS <>", value, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsGreaterThan(String value) {
            addCriterion("B_FLOORS >", value, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsGreaterThanOrEqualTo(String value) {
            addCriterion("B_FLOORS >=", value, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsLessThan(String value) {
            addCriterion("B_FLOORS <", value, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsLessThanOrEqualTo(String value) {
            addCriterion("B_FLOORS <=", value, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsLike(String value) {
            addCriterion("B_FLOORS like", value, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsNotLike(String value) {
            addCriterion("B_FLOORS not like", value, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsIn(List<String> values) {
            addCriterion("B_FLOORS in", values, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsNotIn(List<String> values) {
            addCriterion("B_FLOORS not in", values, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsBetween(String value1, String value2) {
            addCriterion("B_FLOORS between", value1, value2, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBFloorsNotBetween(String value1, String value2) {
            addCriterion("B_FLOORS not between", value1, value2, "bFloors");
            return (Criteria) this;
        }

        public Criteria andBSpaceIsNull() {
            addCriterion("B_SPACE is null");
            return (Criteria) this;
        }

        public Criteria andBSpaceIsNotNull() {
            addCriterion("B_SPACE is not null");
            return (Criteria) this;
        }

        public Criteria andBSpaceEqualTo(String value) {
            addCriterion("B_SPACE =", value, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceNotEqualTo(String value) {
            addCriterion("B_SPACE <>", value, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceGreaterThan(String value) {
            addCriterion("B_SPACE >", value, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceGreaterThanOrEqualTo(String value) {
            addCriterion("B_SPACE >=", value, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceLessThan(String value) {
            addCriterion("B_SPACE <", value, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceLessThanOrEqualTo(String value) {
            addCriterion("B_SPACE <=", value, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceLike(String value) {
            addCriterion("B_SPACE like", value, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceNotLike(String value) {
            addCriterion("B_SPACE not like", value, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceIn(List<String> values) {
            addCriterion("B_SPACE in", values, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceNotIn(List<String> values) {
            addCriterion("B_SPACE not in", values, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceBetween(String value1, String value2) {
            addCriterion("B_SPACE between", value1, value2, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBSpaceNotBetween(String value1, String value2) {
            addCriterion("B_SPACE not between", value1, value2, "bSpace");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsIsNull() {
            addCriterion("B_BUILD_PRJS is null");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsIsNotNull() {
            addCriterion("B_BUILD_PRJS is not null");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsEqualTo(String value) {
            addCriterion("B_BUILD_PRJS =", value, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsNotEqualTo(String value) {
            addCriterion("B_BUILD_PRJS <>", value, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsGreaterThan(String value) {
            addCriterion("B_BUILD_PRJS >", value, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsGreaterThanOrEqualTo(String value) {
            addCriterion("B_BUILD_PRJS >=", value, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsLessThan(String value) {
            addCriterion("B_BUILD_PRJS <", value, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsLessThanOrEqualTo(String value) {
            addCriterion("B_BUILD_PRJS <=", value, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsLike(String value) {
            addCriterion("B_BUILD_PRJS like", value, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsNotLike(String value) {
            addCriterion("B_BUILD_PRJS not like", value, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsIn(List<String> values) {
            addCriterion("B_BUILD_PRJS in", values, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsNotIn(List<String> values) {
            addCriterion("B_BUILD_PRJS not in", values, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsBetween(String value1, String value2) {
            addCriterion("B_BUILD_PRJS between", value1, value2, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBBuildPrjsNotBetween(String value1, String value2) {
            addCriterion("B_BUILD_PRJS not between", value1, value2, "bBuildPrjs");
            return (Criteria) this;
        }

        public Criteria andBUnmsIsNull() {
            addCriterion("B_UNMS is null");
            return (Criteria) this;
        }

        public Criteria andBUnmsIsNotNull() {
            addCriterion("B_UNMS is not null");
            return (Criteria) this;
        }

        public Criteria andBUnmsEqualTo(String value) {
            addCriterion("B_UNMS =", value, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsNotEqualTo(String value) {
            addCriterion("B_UNMS <>", value, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsGreaterThan(String value) {
            addCriterion("B_UNMS >", value, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsGreaterThanOrEqualTo(String value) {
            addCriterion("B_UNMS >=", value, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsLessThan(String value) {
            addCriterion("B_UNMS <", value, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsLessThanOrEqualTo(String value) {
            addCriterion("B_UNMS <=", value, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsLike(String value) {
            addCriterion("B_UNMS like", value, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsNotLike(String value) {
            addCriterion("B_UNMS not like", value, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsIn(List<String> values) {
            addCriterion("B_UNMS in", values, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsNotIn(List<String> values) {
            addCriterion("B_UNMS not in", values, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsBetween(String value1, String value2) {
            addCriterion("B_UNMS between", value1, value2, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBUnmsNotBetween(String value1, String value2) {
            addCriterion("B_UNMS not between", value1, value2, "bUnms");
            return (Criteria) this;
        }

        public Criteria andBFloorssIsNull() {
            addCriterion("B_FLOORSS is null");
            return (Criteria) this;
        }

        public Criteria andBFloorssIsNotNull() {
            addCriterion("B_FLOORSS is not null");
            return (Criteria) this;
        }

        public Criteria andBFloorssEqualTo(String value) {
            addCriterion("B_FLOORSS =", value, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssNotEqualTo(String value) {
            addCriterion("B_FLOORSS <>", value, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssGreaterThan(String value) {
            addCriterion("B_FLOORSS >", value, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssGreaterThanOrEqualTo(String value) {
            addCriterion("B_FLOORSS >=", value, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssLessThan(String value) {
            addCriterion("B_FLOORSS <", value, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssLessThanOrEqualTo(String value) {
            addCriterion("B_FLOORSS <=", value, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssLike(String value) {
            addCriterion("B_FLOORSS like", value, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssNotLike(String value) {
            addCriterion("B_FLOORSS not like", value, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssIn(List<String> values) {
            addCriterion("B_FLOORSS in", values, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssNotIn(List<String> values) {
            addCriterion("B_FLOORSS not in", values, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssBetween(String value1, String value2) {
            addCriterion("B_FLOORSS between", value1, value2, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBFloorssNotBetween(String value1, String value2) {
            addCriterion("B_FLOORSS not between", value1, value2, "bFloorss");
            return (Criteria) this;
        }

        public Criteria andBSpacesIsNull() {
            addCriterion("B_SPACES is null");
            return (Criteria) this;
        }

        public Criteria andBSpacesIsNotNull() {
            addCriterion("B_SPACES is not null");
            return (Criteria) this;
        }

        public Criteria andBSpacesEqualTo(String value) {
            addCriterion("B_SPACES =", value, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesNotEqualTo(String value) {
            addCriterion("B_SPACES <>", value, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesGreaterThan(String value) {
            addCriterion("B_SPACES >", value, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesGreaterThanOrEqualTo(String value) {
            addCriterion("B_SPACES >=", value, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesLessThan(String value) {
            addCriterion("B_SPACES <", value, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesLessThanOrEqualTo(String value) {
            addCriterion("B_SPACES <=", value, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesLike(String value) {
            addCriterion("B_SPACES like", value, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesNotLike(String value) {
            addCriterion("B_SPACES not like", value, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesIn(List<String> values) {
            addCriterion("B_SPACES in", values, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesNotIn(List<String> values) {
            addCriterion("B_SPACES not in", values, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesBetween(String value1, String value2) {
            addCriterion("B_SPACES between", value1, value2, "bSpaces");
            return (Criteria) this;
        }

        public Criteria andBSpacesNotBetween(String value1, String value2) {
            addCriterion("B_SPACES not between", value1, value2, "bSpaces");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 20 14:57:20 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_gt_jsyd_sqb_js
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}