package com.lpcode.modules.blsp.entity;

import java.util.ArrayList;
import java.util.List;

public class FormZjSgxkSqbJsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    protected int start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public FormZjSgxkSqbJsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void setStart(int start) {
        this.start=start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public int getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBIdIsNull() {
            addCriterion("B_ID is null");
            return (Criteria) this;
        }

        public Criteria andBIdIsNotNull() {
            addCriterion("B_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBIdEqualTo(Long value) {
            addCriterion("B_ID =", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdNotEqualTo(Long value) {
            addCriterion("B_ID <>", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdGreaterThan(Long value) {
            addCriterion("B_ID >", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdGreaterThanOrEqualTo(Long value) {
            addCriterion("B_ID >=", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdLessThan(Long value) {
            addCriterion("B_ID <", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdLessThanOrEqualTo(Long value) {
            addCriterion("B_ID <=", value, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdIn(List<Long> values) {
            addCriterion("B_ID in", values, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdNotIn(List<Long> values) {
            addCriterion("B_ID not in", values, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdBetween(Long value1, Long value2) {
            addCriterion("B_ID between", value1, value2, "bId");
            return (Criteria) this;
        }

        public Criteria andBIdNotBetween(Long value1, Long value2) {
            addCriterion("B_ID not between", value1, value2, "bId");
            return (Criteria) this;
        }

        public Criteria andZIdIsNull() {
            addCriterion("Z_ID is null");
            return (Criteria) this;
        }

        public Criteria andZIdIsNotNull() {
            addCriterion("Z_ID is not null");
            return (Criteria) this;
        }

        public Criteria andZIdEqualTo(Long value) {
            addCriterion("Z_ID =", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotEqualTo(Long value) {
            addCriterion("Z_ID <>", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdGreaterThan(Long value) {
            addCriterion("Z_ID >", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Z_ID >=", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLessThan(Long value) {
            addCriterion("Z_ID <", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdLessThanOrEqualTo(Long value) {
            addCriterion("Z_ID <=", value, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdIn(List<Long> values) {
            addCriterion("Z_ID in", values, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotIn(List<Long> values) {
            addCriterion("Z_ID not in", values, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdBetween(Long value1, Long value2) {
            addCriterion("Z_ID between", value1, value2, "zId");
            return (Criteria) this;
        }

        public Criteria andZIdNotBetween(Long value1, Long value2) {
            addCriterion("Z_ID not between", value1, value2, "zId");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteIsNull() {
            addCriterion("B_IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteIsNotNull() {
            addCriterion("B_IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteEqualTo(String value) {
            addCriterion("B_IS_DELETE =", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteNotEqualTo(String value) {
            addCriterion("B_IS_DELETE <>", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteGreaterThan(String value) {
            addCriterion("B_IS_DELETE >", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteGreaterThanOrEqualTo(String value) {
            addCriterion("B_IS_DELETE >=", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteLessThan(String value) {
            addCriterion("B_IS_DELETE <", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteLessThanOrEqualTo(String value) {
            addCriterion("B_IS_DELETE <=", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteLike(String value) {
            addCriterion("B_IS_DELETE like", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteNotLike(String value) {
            addCriterion("B_IS_DELETE not like", value, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteIn(List<String> values) {
            addCriterion("B_IS_DELETE in", values, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteNotIn(List<String> values) {
            addCriterion("B_IS_DELETE not in", values, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteBetween(String value1, String value2) {
            addCriterion("B_IS_DELETE between", value1, value2, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBIsDeleteNotBetween(String value1, String value2) {
            addCriterion("B_IS_DELETE not between", value1, value2, "bIsDelete");
            return (Criteria) this;
        }

        public Criteria andBNameIsNull() {
            addCriterion("B_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBNameIsNotNull() {
            addCriterion("B_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBNameEqualTo(String value) {
            addCriterion("B_NAME =", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameNotEqualTo(String value) {
            addCriterion("B_NAME <>", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameGreaterThan(String value) {
            addCriterion("B_NAME >", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameGreaterThanOrEqualTo(String value) {
            addCriterion("B_NAME >=", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameLessThan(String value) {
            addCriterion("B_NAME <", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameLessThanOrEqualTo(String value) {
            addCriterion("B_NAME <=", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameLike(String value) {
            addCriterion("B_NAME like", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameNotLike(String value) {
            addCriterion("B_NAME not like", value, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameIn(List<String> values) {
            addCriterion("B_NAME in", values, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameNotIn(List<String> values) {
            addCriterion("B_NAME not in", values, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameBetween(String value1, String value2) {
            addCriterion("B_NAME between", value1, value2, "bName");
            return (Criteria) this;
        }

        public Criteria andBNameNotBetween(String value1, String value2) {
            addCriterion("B_NAME not between", value1, value2, "bName");
            return (Criteria) this;
        }

        public Criteria andBPapersIdIsNull() {
            addCriterion("B_PAPERS_ID is null");
            return (Criteria) this;
        }

        public Criteria andBPapersIdIsNotNull() {
            addCriterion("B_PAPERS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBPapersIdEqualTo(String value) {
            addCriterion("B_PAPERS_ID =", value, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdNotEqualTo(String value) {
            addCriterion("B_PAPERS_ID <>", value, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdGreaterThan(String value) {
            addCriterion("B_PAPERS_ID >", value, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdGreaterThanOrEqualTo(String value) {
            addCriterion("B_PAPERS_ID >=", value, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdLessThan(String value) {
            addCriterion("B_PAPERS_ID <", value, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdLessThanOrEqualTo(String value) {
            addCriterion("B_PAPERS_ID <=", value, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdLike(String value) {
            addCriterion("B_PAPERS_ID like", value, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdNotLike(String value) {
            addCriterion("B_PAPERS_ID not like", value, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdIn(List<String> values) {
            addCriterion("B_PAPERS_ID in", values, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdNotIn(List<String> values) {
            addCriterion("B_PAPERS_ID not in", values, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdBetween(String value1, String value2) {
            addCriterion("B_PAPERS_ID between", value1, value2, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBPapersIdNotBetween(String value1, String value2) {
            addCriterion("B_PAPERS_ID not between", value1, value2, "bPapersId");
            return (Criteria) this;
        }

        public Criteria andBDutyIsNull() {
            addCriterion("B_DUTY is null");
            return (Criteria) this;
        }

        public Criteria andBDutyIsNotNull() {
            addCriterion("B_DUTY is not null");
            return (Criteria) this;
        }

        public Criteria andBDutyEqualTo(String value) {
            addCriterion("B_DUTY =", value, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyNotEqualTo(String value) {
            addCriterion("B_DUTY <>", value, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyGreaterThan(String value) {
            addCriterion("B_DUTY >", value, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyGreaterThanOrEqualTo(String value) {
            addCriterion("B_DUTY >=", value, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyLessThan(String value) {
            addCriterion("B_DUTY <", value, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyLessThanOrEqualTo(String value) {
            addCriterion("B_DUTY <=", value, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyLike(String value) {
            addCriterion("B_DUTY like", value, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyNotLike(String value) {
            addCriterion("B_DUTY not like", value, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyIn(List<String> values) {
            addCriterion("B_DUTY in", values, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyNotIn(List<String> values) {
            addCriterion("B_DUTY not in", values, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyBetween(String value1, String value2) {
            addCriterion("B_DUTY between", value1, value2, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBDutyNotBetween(String value1, String value2) {
            addCriterion("B_DUTY not between", value1, value2, "bDuty");
            return (Criteria) this;
        }

        public Criteria andBLinktelIsNull() {
            addCriterion("B_LINKTEL is null");
            return (Criteria) this;
        }

        public Criteria andBLinktelIsNotNull() {
            addCriterion("B_LINKTEL is not null");
            return (Criteria) this;
        }

        public Criteria andBLinktelEqualTo(String value) {
            addCriterion("B_LINKTEL =", value, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelNotEqualTo(String value) {
            addCriterion("B_LINKTEL <>", value, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelGreaterThan(String value) {
            addCriterion("B_LINKTEL >", value, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelGreaterThanOrEqualTo(String value) {
            addCriterion("B_LINKTEL >=", value, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelLessThan(String value) {
            addCriterion("B_LINKTEL <", value, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelLessThanOrEqualTo(String value) {
            addCriterion("B_LINKTEL <=", value, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelLike(String value) {
            addCriterion("B_LINKTEL like", value, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelNotLike(String value) {
            addCriterion("B_LINKTEL not like", value, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelIn(List<String> values) {
            addCriterion("B_LINKTEL in", values, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelNotIn(List<String> values) {
            addCriterion("B_LINKTEL not in", values, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelBetween(String value1, String value2) {
            addCriterion("B_LINKTEL between", value1, value2, "bLinktel");
            return (Criteria) this;
        }

        public Criteria andBLinktelNotBetween(String value1, String value2) {
            addCriterion("B_LINKTEL not between", value1, value2, "bLinktel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 24 13:12:10 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}