package com.lpcode.modules.blsp.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FormQxSjshSqsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    protected int start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public FormQxSjshSqsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setStart(int start) {
        this.start=start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public int getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("CREAT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("CREAT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterion("CREAT_TIME =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterion("CREAT_TIME <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterion("CREAT_TIME >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREAT_TIME >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterion("CREAT_TIME <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREAT_TIME <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterion("CREAT_TIME in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterion("CREAT_TIME not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterion("CREAT_TIME between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREAT_TIME not between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNull() {
            addCriterion("UPDATOR is null");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNotNull() {
            addCriterion("UPDATOR is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatorEqualTo(String value) {
            addCriterion("UPDATOR =", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotEqualTo(String value) {
            addCriterion("UPDATOR <>", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThan(String value) {
            addCriterion("UPDATOR >", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATOR >=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThan(String value) {
            addCriterion("UPDATOR <", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThanOrEqualTo(String value) {
            addCriterion("UPDATOR <=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLike(String value) {
            addCriterion("UPDATOR like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotLike(String value) {
            addCriterion("UPDATOR not like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorIn(List<String> values) {
            addCriterion("UPDATOR in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotIn(List<String> values) {
            addCriterion("UPDATOR not in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorBetween(String value1, String value2) {
            addCriterion("UPDATOR between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotBetween(String value1, String value2) {
            addCriterion("UPDATOR not between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(String value) {
            addCriterion("IS_DELETE =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(String value) {
            addCriterion("IS_DELETE <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(String value) {
            addCriterion("IS_DELETE >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETE >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(String value) {
            addCriterion("IS_DELETE <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETE <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLike(String value) {
            addCriterion("IS_DELETE like", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotLike(String value) {
            addCriterion("IS_DELETE not like", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<String> values) {
            addCriterion("IS_DELETE in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<String> values) {
            addCriterion("IS_DELETE not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(String value1, String value2) {
            addCriterion("IS_DELETE between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(String value1, String value2) {
            addCriterion("IS_DELETE not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andPrjIdIsNull() {
            addCriterion("PRJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andPrjIdIsNotNull() {
            addCriterion("PRJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPrjIdEqualTo(Long value) {
            addCriterion("PRJ_ID =", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdNotEqualTo(Long value) {
            addCriterion("PRJ_ID <>", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdGreaterThan(Long value) {
            addCriterion("PRJ_ID >", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PRJ_ID >=", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdLessThan(Long value) {
            addCriterion("PRJ_ID <", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdLessThanOrEqualTo(Long value) {
            addCriterion("PRJ_ID <=", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdIn(List<Long> values) {
            addCriterion("PRJ_ID in", values, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdNotIn(List<Long> values) {
            addCriterion("PRJ_ID not in", values, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdBetween(Long value1, Long value2) {
            addCriterion("PRJ_ID between", value1, value2, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdNotBetween(Long value1, Long value2) {
            addCriterion("PRJ_ID not between", value1, value2, "prjId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("TASK_ID is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("TASK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Long value) {
            addCriterion("TASK_ID =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Long value) {
            addCriterion("TASK_ID <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Long value) {
            addCriterion("TASK_ID >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TASK_ID >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Long value) {
            addCriterion("TASK_ID <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Long value) {
            addCriterion("TASK_ID <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Long> values) {
            addCriterion("TASK_ID in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Long> values) {
            addCriterion("TASK_ID not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Long value1, Long value2) {
            addCriterion("TASK_ID between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Long value1, Long value2) {
            addCriterion("TASK_ID not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andPrjNameIsNull() {
            addCriterion("PRJ_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPrjNameIsNotNull() {
            addCriterion("PRJ_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPrjNameEqualTo(String value) {
            addCriterion("PRJ_NAME =", value, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameNotEqualTo(String value) {
            addCriterion("PRJ_NAME <>", value, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameGreaterThan(String value) {
            addCriterion("PRJ_NAME >", value, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameGreaterThanOrEqualTo(String value) {
            addCriterion("PRJ_NAME >=", value, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameLessThan(String value) {
            addCriterion("PRJ_NAME <", value, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameLessThanOrEqualTo(String value) {
            addCriterion("PRJ_NAME <=", value, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameLike(String value) {
            addCriterion("PRJ_NAME like", value, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameNotLike(String value) {
            addCriterion("PRJ_NAME not like", value, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameIn(List<String> values) {
            addCriterion("PRJ_NAME in", values, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameNotIn(List<String> values) {
            addCriterion("PRJ_NAME not in", values, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameBetween(String value1, String value2) {
            addCriterion("PRJ_NAME between", value1, value2, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjNameNotBetween(String value1, String value2) {
            addCriterion("PRJ_NAME not between", value1, value2, "prjName");
            return (Criteria) this;
        }

        public Criteria andPrjAddrIsNull() {
            addCriterion("PRJ_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andPrjAddrIsNotNull() {
            addCriterion("PRJ_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andPrjAddrEqualTo(String value) {
            addCriterion("PRJ_ADDR =", value, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrNotEqualTo(String value) {
            addCriterion("PRJ_ADDR <>", value, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrGreaterThan(String value) {
            addCriterion("PRJ_ADDR >", value, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrGreaterThanOrEqualTo(String value) {
            addCriterion("PRJ_ADDR >=", value, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrLessThan(String value) {
            addCriterion("PRJ_ADDR <", value, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrLessThanOrEqualTo(String value) {
            addCriterion("PRJ_ADDR <=", value, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrLike(String value) {
            addCriterion("PRJ_ADDR like", value, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrNotLike(String value) {
            addCriterion("PRJ_ADDR not like", value, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrIn(List<String> values) {
            addCriterion("PRJ_ADDR in", values, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrNotIn(List<String> values) {
            addCriterion("PRJ_ADDR not in", values, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrBetween(String value1, String value2) {
            addCriterion("PRJ_ADDR between", value1, value2, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andPrjAddrNotBetween(String value1, String value2) {
            addCriterion("PRJ_ADDR not between", value1, value2, "prjAddr");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumIsNull() {
            addCriterion("RIDGEPOLE_NUM is null");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumIsNotNull() {
            addCriterion("RIDGEPOLE_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumEqualTo(String value) {
            addCriterion("RIDGEPOLE_NUM =", value, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumNotEqualTo(String value) {
            addCriterion("RIDGEPOLE_NUM <>", value, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumGreaterThan(String value) {
            addCriterion("RIDGEPOLE_NUM >", value, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumGreaterThanOrEqualTo(String value) {
            addCriterion("RIDGEPOLE_NUM >=", value, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumLessThan(String value) {
            addCriterion("RIDGEPOLE_NUM <", value, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumLessThanOrEqualTo(String value) {
            addCriterion("RIDGEPOLE_NUM <=", value, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumLike(String value) {
            addCriterion("RIDGEPOLE_NUM like", value, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumNotLike(String value) {
            addCriterion("RIDGEPOLE_NUM not like", value, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumIn(List<String> values) {
            addCriterion("RIDGEPOLE_NUM in", values, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumNotIn(List<String> values) {
            addCriterion("RIDGEPOLE_NUM not in", values, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumBetween(String value1, String value2) {
            addCriterion("RIDGEPOLE_NUM between", value1, value2, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andRidgepoleNumNotBetween(String value1, String value2) {
            addCriterion("RIDGEPOLE_NUM not between", value1, value2, "ridgepoleNum");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageIsNull() {
            addCriterion("OVERALL_FLOORAGE is null");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageIsNotNull() {
            addCriterion("OVERALL_FLOORAGE is not null");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageEqualTo(String value) {
            addCriterion("OVERALL_FLOORAGE =", value, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageNotEqualTo(String value) {
            addCriterion("OVERALL_FLOORAGE <>", value, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageGreaterThan(String value) {
            addCriterion("OVERALL_FLOORAGE >", value, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageGreaterThanOrEqualTo(String value) {
            addCriterion("OVERALL_FLOORAGE >=", value, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageLessThan(String value) {
            addCriterion("OVERALL_FLOORAGE <", value, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageLessThanOrEqualTo(String value) {
            addCriterion("OVERALL_FLOORAGE <=", value, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageLike(String value) {
            addCriterion("OVERALL_FLOORAGE like", value, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageNotLike(String value) {
            addCriterion("OVERALL_FLOORAGE not like", value, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageIn(List<String> values) {
            addCriterion("OVERALL_FLOORAGE in", values, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageNotIn(List<String> values) {
            addCriterion("OVERALL_FLOORAGE not in", values, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageBetween(String value1, String value2) {
            addCriterion("OVERALL_FLOORAGE between", value1, value2, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andOverallFloorageNotBetween(String value1, String value2) {
            addCriterion("OVERALL_FLOORAGE not between", value1, value2, "overallFloorage");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightIsNull() {
            addCriterion("HEIGHTEST_HEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightIsNotNull() {
            addCriterion("HEIGHTEST_HEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightEqualTo(String value) {
            addCriterion("HEIGHTEST_HEIGHT =", value, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightNotEqualTo(String value) {
            addCriterion("HEIGHTEST_HEIGHT <>", value, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightGreaterThan(String value) {
            addCriterion("HEIGHTEST_HEIGHT >", value, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightGreaterThanOrEqualTo(String value) {
            addCriterion("HEIGHTEST_HEIGHT >=", value, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightLessThan(String value) {
            addCriterion("HEIGHTEST_HEIGHT <", value, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightLessThanOrEqualTo(String value) {
            addCriterion("HEIGHTEST_HEIGHT <=", value, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightLike(String value) {
            addCriterion("HEIGHTEST_HEIGHT like", value, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightNotLike(String value) {
            addCriterion("HEIGHTEST_HEIGHT not like", value, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightIn(List<String> values) {
            addCriterion("HEIGHTEST_HEIGHT in", values, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightNotIn(List<String> values) {
            addCriterion("HEIGHTEST_HEIGHT not in", values, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightBetween(String value1, String value2) {
            addCriterion("HEIGHTEST_HEIGHT between", value1, value2, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andHeightestHeightNotBetween(String value1, String value2) {
            addCriterion("HEIGHTEST_HEIGHT not between", value1, value2, "heightestHeight");
            return (Criteria) this;
        }

        public Criteria andTotalAreaIsNull() {
            addCriterion("TOTAL_AREA is null");
            return (Criteria) this;
        }

        public Criteria andTotalAreaIsNotNull() {
            addCriterion("TOTAL_AREA is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAreaEqualTo(String value) {
            addCriterion("TOTAL_AREA =", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaNotEqualTo(String value) {
            addCriterion("TOTAL_AREA <>", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaGreaterThan(String value) {
            addCriterion("TOTAL_AREA >", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaGreaterThanOrEqualTo(String value) {
            addCriterion("TOTAL_AREA >=", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaLessThan(String value) {
            addCriterion("TOTAL_AREA <", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaLessThanOrEqualTo(String value) {
            addCriterion("TOTAL_AREA <=", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaLike(String value) {
            addCriterion("TOTAL_AREA like", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaNotLike(String value) {
            addCriterion("TOTAL_AREA not like", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaIn(List<String> values) {
            addCriterion("TOTAL_AREA in", values, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaNotIn(List<String> values) {
            addCriterion("TOTAL_AREA not in", values, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaBetween(String value1, String value2) {
            addCriterion("TOTAL_AREA between", value1, value2, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaNotBetween(String value1, String value2) {
            addCriterion("TOTAL_AREA not between", value1, value2, "totalArea");
            return (Criteria) this;
        }

        public Criteria andUseNatureIsNull() {
            addCriterion("USE_NATURE is null");
            return (Criteria) this;
        }

        public Criteria andUseNatureIsNotNull() {
            addCriterion("USE_NATURE is not null");
            return (Criteria) this;
        }

        public Criteria andUseNatureEqualTo(String value) {
            addCriterion("USE_NATURE =", value, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureNotEqualTo(String value) {
            addCriterion("USE_NATURE <>", value, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureGreaterThan(String value) {
            addCriterion("USE_NATURE >", value, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureGreaterThanOrEqualTo(String value) {
            addCriterion("USE_NATURE >=", value, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureLessThan(String value) {
            addCriterion("USE_NATURE <", value, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureLessThanOrEqualTo(String value) {
            addCriterion("USE_NATURE <=", value, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureLike(String value) {
            addCriterion("USE_NATURE like", value, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureNotLike(String value) {
            addCriterion("USE_NATURE not like", value, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureIn(List<String> values) {
            addCriterion("USE_NATURE in", values, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureNotIn(List<String> values) {
            addCriterion("USE_NATURE not in", values, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureBetween(String value1, String value2) {
            addCriterion("USE_NATURE between", value1, value2, "useNature");
            return (Criteria) this;
        }

        public Criteria andUseNatureNotBetween(String value1, String value2) {
            addCriterion("USE_NATURE not between", value1, value2, "useNature");
            return (Criteria) this;
        }

        public Criteria andConstructUnitIsNull() {
            addCriterion("CONSTRUCT_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andConstructUnitIsNotNull() {
            addCriterion("CONSTRUCT_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andConstructUnitEqualTo(String value) {
            addCriterion("CONSTRUCT_UNIT =", value, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitNotEqualTo(String value) {
            addCriterion("CONSTRUCT_UNIT <>", value, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitGreaterThan(String value) {
            addCriterion("CONSTRUCT_UNIT >", value, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitGreaterThanOrEqualTo(String value) {
            addCriterion("CONSTRUCT_UNIT >=", value, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitLessThan(String value) {
            addCriterion("CONSTRUCT_UNIT <", value, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitLessThanOrEqualTo(String value) {
            addCriterion("CONSTRUCT_UNIT <=", value, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitLike(String value) {
            addCriterion("CONSTRUCT_UNIT like", value, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitNotLike(String value) {
            addCriterion("CONSTRUCT_UNIT not like", value, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitIn(List<String> values) {
            addCriterion("CONSTRUCT_UNIT in", values, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitNotIn(List<String> values) {
            addCriterion("CONSTRUCT_UNIT not in", values, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitBetween(String value1, String value2) {
            addCriterion("CONSTRUCT_UNIT between", value1, value2, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructUnitNotBetween(String value1, String value2) {
            addCriterion("CONSTRUCT_UNIT not between", value1, value2, "constructUnit");
            return (Criteria) this;
        }

        public Criteria andConstructAddrIsNull() {
            addCriterion("CONSTRUCT_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andConstructAddrIsNotNull() {
            addCriterion("CONSTRUCT_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andConstructAddrEqualTo(String value) {
            addCriterion("CONSTRUCT_ADDR =", value, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrNotEqualTo(String value) {
            addCriterion("CONSTRUCT_ADDR <>", value, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrGreaterThan(String value) {
            addCriterion("CONSTRUCT_ADDR >", value, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrGreaterThanOrEqualTo(String value) {
            addCriterion("CONSTRUCT_ADDR >=", value, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrLessThan(String value) {
            addCriterion("CONSTRUCT_ADDR <", value, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrLessThanOrEqualTo(String value) {
            addCriterion("CONSTRUCT_ADDR <=", value, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrLike(String value) {
            addCriterion("CONSTRUCT_ADDR like", value, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrNotLike(String value) {
            addCriterion("CONSTRUCT_ADDR not like", value, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrIn(List<String> values) {
            addCriterion("CONSTRUCT_ADDR in", values, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrNotIn(List<String> values) {
            addCriterion("CONSTRUCT_ADDR not in", values, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrBetween(String value1, String value2) {
            addCriterion("CONSTRUCT_ADDR between", value1, value2, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructAddrNotBetween(String value1, String value2) {
            addCriterion("CONSTRUCT_ADDR not between", value1, value2, "constructAddr");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeIsNull() {
            addCriterion("CONSTRUCT_POSTCODE is null");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeIsNotNull() {
            addCriterion("CONSTRUCT_POSTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeEqualTo(String value) {
            addCriterion("CONSTRUCT_POSTCODE =", value, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeNotEqualTo(String value) {
            addCriterion("CONSTRUCT_POSTCODE <>", value, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeGreaterThan(String value) {
            addCriterion("CONSTRUCT_POSTCODE >", value, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CONSTRUCT_POSTCODE >=", value, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeLessThan(String value) {
            addCriterion("CONSTRUCT_POSTCODE <", value, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeLessThanOrEqualTo(String value) {
            addCriterion("CONSTRUCT_POSTCODE <=", value, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeLike(String value) {
            addCriterion("CONSTRUCT_POSTCODE like", value, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeNotLike(String value) {
            addCriterion("CONSTRUCT_POSTCODE not like", value, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeIn(List<String> values) {
            addCriterion("CONSTRUCT_POSTCODE in", values, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeNotIn(List<String> values) {
            addCriterion("CONSTRUCT_POSTCODE not in", values, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeBetween(String value1, String value2) {
            addCriterion("CONSTRUCT_POSTCODE between", value1, value2, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructPostcodeNotBetween(String value1, String value2) {
            addCriterion("CONSTRUCT_POSTCODE not between", value1, value2, "constructPostcode");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanIsNull() {
            addCriterion("CONSTRUCT_LINKMAN is null");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanIsNotNull() {
            addCriterion("CONSTRUCT_LINKMAN is not null");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanEqualTo(String value) {
            addCriterion("CONSTRUCT_LINKMAN =", value, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanNotEqualTo(String value) {
            addCriterion("CONSTRUCT_LINKMAN <>", value, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanGreaterThan(String value) {
            addCriterion("CONSTRUCT_LINKMAN >", value, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("CONSTRUCT_LINKMAN >=", value, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanLessThan(String value) {
            addCriterion("CONSTRUCT_LINKMAN <", value, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanLessThanOrEqualTo(String value) {
            addCriterion("CONSTRUCT_LINKMAN <=", value, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanLike(String value) {
            addCriterion("CONSTRUCT_LINKMAN like", value, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanNotLike(String value) {
            addCriterion("CONSTRUCT_LINKMAN not like", value, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanIn(List<String> values) {
            addCriterion("CONSTRUCT_LINKMAN in", values, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanNotIn(List<String> values) {
            addCriterion("CONSTRUCT_LINKMAN not in", values, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanBetween(String value1, String value2) {
            addCriterion("CONSTRUCT_LINKMAN between", value1, value2, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinkmanNotBetween(String value1, String value2) {
            addCriterion("CONSTRUCT_LINKMAN not between", value1, value2, "constructLinkman");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelIsNull() {
            addCriterion("CONSTRUCT_LINKTEL is null");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelIsNotNull() {
            addCriterion("CONSTRUCT_LINKTEL is not null");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelEqualTo(String value) {
            addCriterion("CONSTRUCT_LINKTEL =", value, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelNotEqualTo(String value) {
            addCriterion("CONSTRUCT_LINKTEL <>", value, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelGreaterThan(String value) {
            addCriterion("CONSTRUCT_LINKTEL >", value, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelGreaterThanOrEqualTo(String value) {
            addCriterion("CONSTRUCT_LINKTEL >=", value, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelLessThan(String value) {
            addCriterion("CONSTRUCT_LINKTEL <", value, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelLessThanOrEqualTo(String value) {
            addCriterion("CONSTRUCT_LINKTEL <=", value, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelLike(String value) {
            addCriterion("CONSTRUCT_LINKTEL like", value, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelNotLike(String value) {
            addCriterion("CONSTRUCT_LINKTEL not like", value, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelIn(List<String> values) {
            addCriterion("CONSTRUCT_LINKTEL in", values, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelNotIn(List<String> values) {
            addCriterion("CONSTRUCT_LINKTEL not in", values, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelBetween(String value1, String value2) {
            addCriterion("CONSTRUCT_LINKTEL between", value1, value2, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andConstructLinktelNotBetween(String value1, String value2) {
            addCriterion("CONSTRUCT_LINKTEL not between", value1, value2, "constructLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignUnitIsNull() {
            addCriterion("DESIGN_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andDesignUnitIsNotNull() {
            addCriterion("DESIGN_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andDesignUnitEqualTo(String value) {
            addCriterion("DESIGN_UNIT =", value, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitNotEqualTo(String value) {
            addCriterion("DESIGN_UNIT <>", value, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitGreaterThan(String value) {
            addCriterion("DESIGN_UNIT >", value, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_UNIT >=", value, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitLessThan(String value) {
            addCriterion("DESIGN_UNIT <", value, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_UNIT <=", value, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitLike(String value) {
            addCriterion("DESIGN_UNIT like", value, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitNotLike(String value) {
            addCriterion("DESIGN_UNIT not like", value, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitIn(List<String> values) {
            addCriterion("DESIGN_UNIT in", values, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitNotIn(List<String> values) {
            addCriterion("DESIGN_UNIT not in", values, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitBetween(String value1, String value2) {
            addCriterion("DESIGN_UNIT between", value1, value2, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignUnitNotBetween(String value1, String value2) {
            addCriterion("DESIGN_UNIT not between", value1, value2, "designUnit");
            return (Criteria) this;
        }

        public Criteria andDesignAddrIsNull() {
            addCriterion("DESIGN_ADDR is null");
            return (Criteria) this;
        }

        public Criteria andDesignAddrIsNotNull() {
            addCriterion("DESIGN_ADDR is not null");
            return (Criteria) this;
        }

        public Criteria andDesignAddrEqualTo(String value) {
            addCriterion("DESIGN_ADDR =", value, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrNotEqualTo(String value) {
            addCriterion("DESIGN_ADDR <>", value, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrGreaterThan(String value) {
            addCriterion("DESIGN_ADDR >", value, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_ADDR >=", value, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrLessThan(String value) {
            addCriterion("DESIGN_ADDR <", value, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_ADDR <=", value, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrLike(String value) {
            addCriterion("DESIGN_ADDR like", value, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrNotLike(String value) {
            addCriterion("DESIGN_ADDR not like", value, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrIn(List<String> values) {
            addCriterion("DESIGN_ADDR in", values, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrNotIn(List<String> values) {
            addCriterion("DESIGN_ADDR not in", values, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrBetween(String value1, String value2) {
            addCriterion("DESIGN_ADDR between", value1, value2, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignAddrNotBetween(String value1, String value2) {
            addCriterion("DESIGN_ADDR not between", value1, value2, "designAddr");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeIsNull() {
            addCriterion("DESIGN_POSTCODE is null");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeIsNotNull() {
            addCriterion("DESIGN_POSTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeEqualTo(String value) {
            addCriterion("DESIGN_POSTCODE =", value, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeNotEqualTo(String value) {
            addCriterion("DESIGN_POSTCODE <>", value, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeGreaterThan(String value) {
            addCriterion("DESIGN_POSTCODE >", value, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_POSTCODE >=", value, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeLessThan(String value) {
            addCriterion("DESIGN_POSTCODE <", value, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_POSTCODE <=", value, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeLike(String value) {
            addCriterion("DESIGN_POSTCODE like", value, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeNotLike(String value) {
            addCriterion("DESIGN_POSTCODE not like", value, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeIn(List<String> values) {
            addCriterion("DESIGN_POSTCODE in", values, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeNotIn(List<String> values) {
            addCriterion("DESIGN_POSTCODE not in", values, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeBetween(String value1, String value2) {
            addCriterion("DESIGN_POSTCODE between", value1, value2, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignPostcodeNotBetween(String value1, String value2) {
            addCriterion("DESIGN_POSTCODE not between", value1, value2, "designPostcode");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdIsNull() {
            addCriterion("DESIGN_LICENSE_ID is null");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdIsNotNull() {
            addCriterion("DESIGN_LICENSE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdEqualTo(String value) {
            addCriterion("DESIGN_LICENSE_ID =", value, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdNotEqualTo(String value) {
            addCriterion("DESIGN_LICENSE_ID <>", value, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdGreaterThan(String value) {
            addCriterion("DESIGN_LICENSE_ID >", value, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_LICENSE_ID >=", value, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdLessThan(String value) {
            addCriterion("DESIGN_LICENSE_ID <", value, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_LICENSE_ID <=", value, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdLike(String value) {
            addCriterion("DESIGN_LICENSE_ID like", value, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdNotLike(String value) {
            addCriterion("DESIGN_LICENSE_ID not like", value, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdIn(List<String> values) {
            addCriterion("DESIGN_LICENSE_ID in", values, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdNotIn(List<String> values) {
            addCriterion("DESIGN_LICENSE_ID not in", values, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdBetween(String value1, String value2) {
            addCriterion("DESIGN_LICENSE_ID between", value1, value2, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseIdNotBetween(String value1, String value2) {
            addCriterion("DESIGN_LICENSE_ID not between", value1, value2, "designLicenseId");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankIsNull() {
            addCriterion("DESIGN_LICENSE_RANK is null");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankIsNotNull() {
            addCriterion("DESIGN_LICENSE_RANK is not null");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankEqualTo(String value) {
            addCriterion("DESIGN_LICENSE_RANK =", value, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankNotEqualTo(String value) {
            addCriterion("DESIGN_LICENSE_RANK <>", value, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankGreaterThan(String value) {
            addCriterion("DESIGN_LICENSE_RANK >", value, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_LICENSE_RANK >=", value, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankLessThan(String value) {
            addCriterion("DESIGN_LICENSE_RANK <", value, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_LICENSE_RANK <=", value, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankLike(String value) {
            addCriterion("DESIGN_LICENSE_RANK like", value, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankNotLike(String value) {
            addCriterion("DESIGN_LICENSE_RANK not like", value, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankIn(List<String> values) {
            addCriterion("DESIGN_LICENSE_RANK in", values, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankNotIn(List<String> values) {
            addCriterion("DESIGN_LICENSE_RANK not in", values, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankBetween(String value1, String value2) {
            addCriterion("DESIGN_LICENSE_RANK between", value1, value2, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLicenseRankNotBetween(String value1, String value2) {
            addCriterion("DESIGN_LICENSE_RANK not between", value1, value2, "designLicenseRank");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanIsNull() {
            addCriterion("DESIGN_LINKMAN is null");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanIsNotNull() {
            addCriterion("DESIGN_LINKMAN is not null");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanEqualTo(String value) {
            addCriterion("DESIGN_LINKMAN =", value, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanNotEqualTo(String value) {
            addCriterion("DESIGN_LINKMAN <>", value, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanGreaterThan(String value) {
            addCriterion("DESIGN_LINKMAN >", value, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_LINKMAN >=", value, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanLessThan(String value) {
            addCriterion("DESIGN_LINKMAN <", value, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_LINKMAN <=", value, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanLike(String value) {
            addCriterion("DESIGN_LINKMAN like", value, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanNotLike(String value) {
            addCriterion("DESIGN_LINKMAN not like", value, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanIn(List<String> values) {
            addCriterion("DESIGN_LINKMAN in", values, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanNotIn(List<String> values) {
            addCriterion("DESIGN_LINKMAN not in", values, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanBetween(String value1, String value2) {
            addCriterion("DESIGN_LINKMAN between", value1, value2, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinkmanNotBetween(String value1, String value2) {
            addCriterion("DESIGN_LINKMAN not between", value1, value2, "designLinkman");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelIsNull() {
            addCriterion("DESIGN_LINKTEL is null");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelIsNotNull() {
            addCriterion("DESIGN_LINKTEL is not null");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelEqualTo(String value) {
            addCriterion("DESIGN_LINKTEL =", value, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelNotEqualTo(String value) {
            addCriterion("DESIGN_LINKTEL <>", value, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelGreaterThan(String value) {
            addCriterion("DESIGN_LINKTEL >", value, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_LINKTEL >=", value, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelLessThan(String value) {
            addCriterion("DESIGN_LINKTEL <", value, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_LINKTEL <=", value, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelLike(String value) {
            addCriterion("DESIGN_LINKTEL like", value, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelNotLike(String value) {
            addCriterion("DESIGN_LINKTEL not like", value, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelIn(List<String> values) {
            addCriterion("DESIGN_LINKTEL in", values, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelNotIn(List<String> values) {
            addCriterion("DESIGN_LINKTEL not in", values, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelBetween(String value1, String value2) {
            addCriterion("DESIGN_LINKTEL between", value1, value2, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignLinktelNotBetween(String value1, String value2) {
            addCriterion("DESIGN_LINKTEL not between", value1, value2, "designLinktel");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdIsNull() {
            addCriterion("DESIGN_CPLM_ID is null");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdIsNotNull() {
            addCriterion("DESIGN_CPLM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdEqualTo(String value) {
            addCriterion("DESIGN_CPLM_ID =", value, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdNotEqualTo(String value) {
            addCriterion("DESIGN_CPLM_ID <>", value, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdGreaterThan(String value) {
            addCriterion("DESIGN_CPLM_ID >", value, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdGreaterThanOrEqualTo(String value) {
            addCriterion("DESIGN_CPLM_ID >=", value, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdLessThan(String value) {
            addCriterion("DESIGN_CPLM_ID <", value, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdLessThanOrEqualTo(String value) {
            addCriterion("DESIGN_CPLM_ID <=", value, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdLike(String value) {
            addCriterion("DESIGN_CPLM_ID like", value, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdNotLike(String value) {
            addCriterion("DESIGN_CPLM_ID not like", value, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdIn(List<String> values) {
            addCriterion("DESIGN_CPLM_ID in", values, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdNotIn(List<String> values) {
            addCriterion("DESIGN_CPLM_ID not in", values, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdBetween(String value1, String value2) {
            addCriterion("DESIGN_CPLM_ID between", value1, value2, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andDesignCplmIdNotBetween(String value1, String value2) {
            addCriterion("DESIGN_CPLM_ID not between", value1, value2, "designCplmId");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisIsNull() {
            addCriterion("PLAN_SYNOPSIS is null");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisIsNotNull() {
            addCriterion("PLAN_SYNOPSIS is not null");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisEqualTo(String value) {
            addCriterion("PLAN_SYNOPSIS =", value, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisNotEqualTo(String value) {
            addCriterion("PLAN_SYNOPSIS <>", value, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisGreaterThan(String value) {
            addCriterion("PLAN_SYNOPSIS >", value, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisGreaterThanOrEqualTo(String value) {
            addCriterion("PLAN_SYNOPSIS >=", value, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisLessThan(String value) {
            addCriterion("PLAN_SYNOPSIS <", value, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisLessThanOrEqualTo(String value) {
            addCriterion("PLAN_SYNOPSIS <=", value, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisLike(String value) {
            addCriterion("PLAN_SYNOPSIS like", value, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisNotLike(String value) {
            addCriterion("PLAN_SYNOPSIS not like", value, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisIn(List<String> values) {
            addCriterion("PLAN_SYNOPSIS in", values, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisNotIn(List<String> values) {
            addCriterion("PLAN_SYNOPSIS not in", values, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisBetween(String value1, String value2) {
            addCriterion("PLAN_SYNOPSIS between", value1, value2, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanSynopsisNotBetween(String value1, String value2) {
            addCriterion("PLAN_SYNOPSIS not between", value1, value2, "planSynopsis");
            return (Criteria) this;
        }

        public Criteria andPlanAgentIsNull() {
            addCriterion("PLAN_AGENT is null");
            return (Criteria) this;
        }

        public Criteria andPlanAgentIsNotNull() {
            addCriterion("PLAN_AGENT is not null");
            return (Criteria) this;
        }

        public Criteria andPlanAgentEqualTo(String value) {
            addCriterion("PLAN_AGENT =", value, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentNotEqualTo(String value) {
            addCriterion("PLAN_AGENT <>", value, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentGreaterThan(String value) {
            addCriterion("PLAN_AGENT >", value, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentGreaterThanOrEqualTo(String value) {
            addCriterion("PLAN_AGENT >=", value, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentLessThan(String value) {
            addCriterion("PLAN_AGENT <", value, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentLessThanOrEqualTo(String value) {
            addCriterion("PLAN_AGENT <=", value, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentLike(String value) {
            addCriterion("PLAN_AGENT like", value, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentNotLike(String value) {
            addCriterion("PLAN_AGENT not like", value, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentIn(List<String> values) {
            addCriterion("PLAN_AGENT in", values, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentNotIn(List<String> values) {
            addCriterion("PLAN_AGENT not in", values, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentBetween(String value1, String value2) {
            addCriterion("PLAN_AGENT between", value1, value2, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanAgentNotBetween(String value1, String value2) {
            addCriterion("PLAN_AGENT not between", value1, value2, "planAgent");
            return (Criteria) this;
        }

        public Criteria andPlanDateIsNull() {
            addCriterion("PLAN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPlanDateIsNotNull() {
            addCriterion("PLAN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPlanDateEqualTo(Date value) {
            addCriterion("PLAN_DATE =", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateNotEqualTo(Date value) {
            addCriterion("PLAN_DATE <>", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateGreaterThan(Date value) {
            addCriterion("PLAN_DATE >", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateGreaterThanOrEqualTo(Date value) {
            addCriterion("PLAN_DATE >=", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateLessThan(Date value) {
            addCriterion("PLAN_DATE <", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateLessThanOrEqualTo(Date value) {
            addCriterion("PLAN_DATE <=", value, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateIn(List<Date> values) {
            addCriterion("PLAN_DATE in", values, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateNotIn(List<Date> values) {
            addCriterion("PLAN_DATE not in", values, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateBetween(Date value1, Date value2) {
            addCriterion("PLAN_DATE between", value1, value2, "planDate");
            return (Criteria) this;
        }

        public Criteria andPlanDateNotBetween(Date value1, Date value2) {
            addCriterion("PLAN_DATE not between", value1, value2, "planDate");
            return (Criteria) this;
        }

        public Criteria andApplyUnitIsNull() {
            addCriterion("APPLY_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andApplyUnitIsNotNull() {
            addCriterion("APPLY_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andApplyUnitEqualTo(String value) {
            addCriterion("APPLY_UNIT =", value, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitNotEqualTo(String value) {
            addCriterion("APPLY_UNIT <>", value, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitGreaterThan(String value) {
            addCriterion("APPLY_UNIT >", value, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_UNIT >=", value, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitLessThan(String value) {
            addCriterion("APPLY_UNIT <", value, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitLessThanOrEqualTo(String value) {
            addCriterion("APPLY_UNIT <=", value, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitLike(String value) {
            addCriterion("APPLY_UNIT like", value, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitNotLike(String value) {
            addCriterion("APPLY_UNIT not like", value, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitIn(List<String> values) {
            addCriterion("APPLY_UNIT in", values, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitNotIn(List<String> values) {
            addCriterion("APPLY_UNIT not in", values, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitBetween(String value1, String value2) {
            addCriterion("APPLY_UNIT between", value1, value2, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyUnitNotBetween(String value1, String value2) {
            addCriterion("APPLY_UNIT not between", value1, value2, "applyUnit");
            return (Criteria) this;
        }

        public Criteria andApplyAgentIsNull() {
            addCriterion("APPLY_AGENT is null");
            return (Criteria) this;
        }

        public Criteria andApplyAgentIsNotNull() {
            addCriterion("APPLY_AGENT is not null");
            return (Criteria) this;
        }

        public Criteria andApplyAgentEqualTo(String value) {
            addCriterion("APPLY_AGENT =", value, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentNotEqualTo(String value) {
            addCriterion("APPLY_AGENT <>", value, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentGreaterThan(String value) {
            addCriterion("APPLY_AGENT >", value, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_AGENT >=", value, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentLessThan(String value) {
            addCriterion("APPLY_AGENT <", value, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentLessThanOrEqualTo(String value) {
            addCriterion("APPLY_AGENT <=", value, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentLike(String value) {
            addCriterion("APPLY_AGENT like", value, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentNotLike(String value) {
            addCriterion("APPLY_AGENT not like", value, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentIn(List<String> values) {
            addCriterion("APPLY_AGENT in", values, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentNotIn(List<String> values) {
            addCriterion("APPLY_AGENT not in", values, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentBetween(String value1, String value2) {
            addCriterion("APPLY_AGENT between", value1, value2, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyAgentNotBetween(String value1, String value2) {
            addCriterion("APPLY_AGENT not between", value1, value2, "applyAgent");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNull() {
            addCriterion("APPLY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andApplyDateIsNotNull() {
            addCriterion("APPLY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDateEqualTo(Date value) {
            addCriterion("APPLY_DATE =", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotEqualTo(Date value) {
            addCriterion("APPLY_DATE <>", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThan(Date value) {
            addCriterion("APPLY_DATE >", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("APPLY_DATE >=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThan(Date value) {
            addCriterion("APPLY_DATE <", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateLessThanOrEqualTo(Date value) {
            addCriterion("APPLY_DATE <=", value, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateIn(List<Date> values) {
            addCriterion("APPLY_DATE in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotIn(List<Date> values) {
            addCriterion("APPLY_DATE not in", values, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateBetween(Date value1, Date value2) {
            addCriterion("APPLY_DATE between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDateNotBetween(Date value1, Date value2) {
            addCriterion("APPLY_DATE not between", value1, value2, "applyDate");
            return (Criteria) this;
        }

        public Criteria andApplyDatesIsNull() {
            addCriterion("APPLY_DATES is null");
            return (Criteria) this;
        }

        public Criteria andApplyDatesIsNotNull() {
            addCriterion("APPLY_DATES is not null");
            return (Criteria) this;
        }

        public Criteria andApplyDatesEqualTo(Date value) {
            addCriterion("APPLY_DATES =", value, "applyDates");
            return (Criteria) this;
        }

        public Criteria andApplyDatesNotEqualTo(Date value) {
            addCriterion("APPLY_DATES <>", value, "applyDates");
            return (Criteria) this;
        }

        public Criteria andApplyDatesGreaterThan(Date value) {
            addCriterion("APPLY_DATES >", value, "applyDates");
            return (Criteria) this;
        }

        public Criteria andApplyDatesGreaterThanOrEqualTo(Date value) {
            addCriterion("APPLY_DATES >=", value, "applyDates");
            return (Criteria) this;
        }

        public Criteria andApplyDatesLessThan(Date value) {
            addCriterion("APPLY_DATES <", value, "applyDates");
            return (Criteria) this;
        }

        public Criteria andApplyDatesLessThanOrEqualTo(Date value) {
            addCriterion("APPLY_DATES <=", value, "applyDates");
            return (Criteria) this;
        }

        public Criteria andApplyDatesIn(List<Date> values) {
            addCriterion("APPLY_DATES in", values, "applyDates");
            return (Criteria) this;
        }

        public Criteria andApplyDatesNotIn(List<Date> values) {
            addCriterion("APPLY_DATES not in", values, "applyDates");
            return (Criteria) this;
        }

        public Criteria andApplyDatesBetween(Date value1, Date value2) {
            addCriterion("APPLY_DATES between", value1, value2, "applyDates");
            return (Criteria) this;
        }

        public Criteria andApplyDatesNotBetween(Date value1, Date value2) {
            addCriterion("APPLY_DATES not between", value1, value2, "applyDates");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 20 18:32:05 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_qx_sjsh_sqs
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}