package com.lpcode.modules.blsp.entity;

import java.util.Date;

public class FormQxSjshSqs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.CREATOR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.UPDATOR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.PRJ_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private Long prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.TASK_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.PRJ_NAME
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String prjName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.PRJ_ADDR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String prjAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.RIDGEPOLE_NUM
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String ridgepoleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.OVERALL_FLOORAGE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String overallFloorage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.HEIGHTEST_HEIGHT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String heightestHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.TOTAL_AREA
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String totalArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.USE_NATURE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String useNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.CONSTRUCT_UNIT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String constructUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.CONSTRUCT_ADDR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String constructAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.CONSTRUCT_POSTCODE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String constructPostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.CONSTRUCT_LINKMAN
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String constructLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.CONSTRUCT_LINKTEL
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String constructLinktel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.DESIGN_UNIT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String designUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.DESIGN_ADDR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String designAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.DESIGN_POSTCODE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String designPostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.DESIGN_LICENSE_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String designLicenseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.DESIGN_LICENSE_RANK
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String designLicenseRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.DESIGN_LINKMAN
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String designLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.DESIGN_LINKTEL
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String designLinktel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.DESIGN_CPLM_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String designCplmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.PLAN_SYNOPSIS
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String planSynopsis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.PLAN_AGENT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String planAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.PLAN_DATE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private Date planDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.APPLY_UNIT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String applyUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.APPLY_AGENT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private String applyAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.APPLY_DATE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private Date applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjsh_sqs.APPLY_DATES
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    private Date applyDates;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.ID
     *
     * @return the value of form_qx_sjsh_sqs.ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.ID
     *
     * @param id the value for form_qx_sjsh_sqs.ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.CREAT_TIME
     *
     * @return the value of form_qx_sjsh_sqs.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.CREAT_TIME
     *
     * @param creatTime the value for form_qx_sjsh_sqs.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.CREATOR
     *
     * @return the value of form_qx_sjsh_sqs.CREATOR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.CREATOR
     *
     * @param creator the value for form_qx_sjsh_sqs.CREATOR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.UPDATE_TIME
     *
     * @return the value of form_qx_sjsh_sqs.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.UPDATE_TIME
     *
     * @param updateTime the value for form_qx_sjsh_sqs.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.UPDATOR
     *
     * @return the value of form_qx_sjsh_sqs.UPDATOR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.UPDATOR
     *
     * @param updator the value for form_qx_sjsh_sqs.UPDATOR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.IS_DELETE
     *
     * @return the value of form_qx_sjsh_sqs.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.IS_DELETE
     *
     * @param isDelete the value for form_qx_sjsh_sqs.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.PRJ_ID
     *
     * @return the value of form_qx_sjsh_sqs.PRJ_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public Long getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.PRJ_ID
     *
     * @param prjId the value for form_qx_sjsh_sqs.PRJ_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setPrjId(Long prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.TASK_ID
     *
     * @return the value of form_qx_sjsh_sqs.TASK_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.TASK_ID
     *
     * @param taskId the value for form_qx_sjsh_sqs.TASK_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.PRJ_NAME
     *
     * @return the value of form_qx_sjsh_sqs.PRJ_NAME
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getPrjName() {
        return prjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.PRJ_NAME
     *
     * @param prjName the value for form_qx_sjsh_sqs.PRJ_NAME
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setPrjName(String prjName) {
        this.prjName = prjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.PRJ_ADDR
     *
     * @return the value of form_qx_sjsh_sqs.PRJ_ADDR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getPrjAddr() {
        return prjAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.PRJ_ADDR
     *
     * @param prjAddr the value for form_qx_sjsh_sqs.PRJ_ADDR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setPrjAddr(String prjAddr) {
        this.prjAddr = prjAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.RIDGEPOLE_NUM
     *
     * @return the value of form_qx_sjsh_sqs.RIDGEPOLE_NUM
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getRidgepoleNum() {
        return ridgepoleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.RIDGEPOLE_NUM
     *
     * @param ridgepoleNum the value for form_qx_sjsh_sqs.RIDGEPOLE_NUM
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setRidgepoleNum(String ridgepoleNum) {
        this.ridgepoleNum = ridgepoleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.OVERALL_FLOORAGE
     *
     * @return the value of form_qx_sjsh_sqs.OVERALL_FLOORAGE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getOverallFloorage() {
        return overallFloorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.OVERALL_FLOORAGE
     *
     * @param overallFloorage the value for form_qx_sjsh_sqs.OVERALL_FLOORAGE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setOverallFloorage(String overallFloorage) {
        this.overallFloorage = overallFloorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.HEIGHTEST_HEIGHT
     *
     * @return the value of form_qx_sjsh_sqs.HEIGHTEST_HEIGHT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getHeightestHeight() {
        return heightestHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.HEIGHTEST_HEIGHT
     *
     * @param heightestHeight the value for form_qx_sjsh_sqs.HEIGHTEST_HEIGHT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setHeightestHeight(String heightestHeight) {
        this.heightestHeight = heightestHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.TOTAL_AREA
     *
     * @return the value of form_qx_sjsh_sqs.TOTAL_AREA
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getTotalArea() {
        return totalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.TOTAL_AREA
     *
     * @param totalArea the value for form_qx_sjsh_sqs.TOTAL_AREA
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setTotalArea(String totalArea) {
        this.totalArea = totalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.USE_NATURE
     *
     * @return the value of form_qx_sjsh_sqs.USE_NATURE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getUseNature() {
        return useNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.USE_NATURE
     *
     * @param useNature the value for form_qx_sjsh_sqs.USE_NATURE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setUseNature(String useNature) {
        this.useNature = useNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.CONSTRUCT_UNIT
     *
     * @return the value of form_qx_sjsh_sqs.CONSTRUCT_UNIT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getConstructUnit() {
        return constructUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.CONSTRUCT_UNIT
     *
     * @param constructUnit the value for form_qx_sjsh_sqs.CONSTRUCT_UNIT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setConstructUnit(String constructUnit) {
        this.constructUnit = constructUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.CONSTRUCT_ADDR
     *
     * @return the value of form_qx_sjsh_sqs.CONSTRUCT_ADDR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getConstructAddr() {
        return constructAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.CONSTRUCT_ADDR
     *
     * @param constructAddr the value for form_qx_sjsh_sqs.CONSTRUCT_ADDR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setConstructAddr(String constructAddr) {
        this.constructAddr = constructAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.CONSTRUCT_POSTCODE
     *
     * @return the value of form_qx_sjsh_sqs.CONSTRUCT_POSTCODE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getConstructPostcode() {
        return constructPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.CONSTRUCT_POSTCODE
     *
     * @param constructPostcode the value for form_qx_sjsh_sqs.CONSTRUCT_POSTCODE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setConstructPostcode(String constructPostcode) {
        this.constructPostcode = constructPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.CONSTRUCT_LINKMAN
     *
     * @return the value of form_qx_sjsh_sqs.CONSTRUCT_LINKMAN
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getConstructLinkman() {
        return constructLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.CONSTRUCT_LINKMAN
     *
     * @param constructLinkman the value for form_qx_sjsh_sqs.CONSTRUCT_LINKMAN
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setConstructLinkman(String constructLinkman) {
        this.constructLinkman = constructLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.CONSTRUCT_LINKTEL
     *
     * @return the value of form_qx_sjsh_sqs.CONSTRUCT_LINKTEL
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getConstructLinktel() {
        return constructLinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.CONSTRUCT_LINKTEL
     *
     * @param constructLinktel the value for form_qx_sjsh_sqs.CONSTRUCT_LINKTEL
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setConstructLinktel(String constructLinktel) {
        this.constructLinktel = constructLinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.DESIGN_UNIT
     *
     * @return the value of form_qx_sjsh_sqs.DESIGN_UNIT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getDesignUnit() {
        return designUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.DESIGN_UNIT
     *
     * @param designUnit the value for form_qx_sjsh_sqs.DESIGN_UNIT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setDesignUnit(String designUnit) {
        this.designUnit = designUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.DESIGN_ADDR
     *
     * @return the value of form_qx_sjsh_sqs.DESIGN_ADDR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getDesignAddr() {
        return designAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.DESIGN_ADDR
     *
     * @param designAddr the value for form_qx_sjsh_sqs.DESIGN_ADDR
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setDesignAddr(String designAddr) {
        this.designAddr = designAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.DESIGN_POSTCODE
     *
     * @return the value of form_qx_sjsh_sqs.DESIGN_POSTCODE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getDesignPostcode() {
        return designPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.DESIGN_POSTCODE
     *
     * @param designPostcode the value for form_qx_sjsh_sqs.DESIGN_POSTCODE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setDesignPostcode(String designPostcode) {
        this.designPostcode = designPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.DESIGN_LICENSE_ID
     *
     * @return the value of form_qx_sjsh_sqs.DESIGN_LICENSE_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getDesignLicenseId() {
        return designLicenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.DESIGN_LICENSE_ID
     *
     * @param designLicenseId the value for form_qx_sjsh_sqs.DESIGN_LICENSE_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setDesignLicenseId(String designLicenseId) {
        this.designLicenseId = designLicenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.DESIGN_LICENSE_RANK
     *
     * @return the value of form_qx_sjsh_sqs.DESIGN_LICENSE_RANK
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getDesignLicenseRank() {
        return designLicenseRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.DESIGN_LICENSE_RANK
     *
     * @param designLicenseRank the value for form_qx_sjsh_sqs.DESIGN_LICENSE_RANK
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setDesignLicenseRank(String designLicenseRank) {
        this.designLicenseRank = designLicenseRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.DESIGN_LINKMAN
     *
     * @return the value of form_qx_sjsh_sqs.DESIGN_LINKMAN
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getDesignLinkman() {
        return designLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.DESIGN_LINKMAN
     *
     * @param designLinkman the value for form_qx_sjsh_sqs.DESIGN_LINKMAN
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setDesignLinkman(String designLinkman) {
        this.designLinkman = designLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.DESIGN_LINKTEL
     *
     * @return the value of form_qx_sjsh_sqs.DESIGN_LINKTEL
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getDesignLinktel() {
        return designLinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.DESIGN_LINKTEL
     *
     * @param designLinktel the value for form_qx_sjsh_sqs.DESIGN_LINKTEL
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setDesignLinktel(String designLinktel) {
        this.designLinktel = designLinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.DESIGN_CPLM_ID
     *
     * @return the value of form_qx_sjsh_sqs.DESIGN_CPLM_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getDesignCplmId() {
        return designCplmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.DESIGN_CPLM_ID
     *
     * @param designCplmId the value for form_qx_sjsh_sqs.DESIGN_CPLM_ID
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setDesignCplmId(String designCplmId) {
        this.designCplmId = designCplmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.PLAN_SYNOPSIS
     *
     * @return the value of form_qx_sjsh_sqs.PLAN_SYNOPSIS
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getPlanSynopsis() {
        return planSynopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.PLAN_SYNOPSIS
     *
     * @param planSynopsis the value for form_qx_sjsh_sqs.PLAN_SYNOPSIS
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setPlanSynopsis(String planSynopsis) {
        this.planSynopsis = planSynopsis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.PLAN_AGENT
     *
     * @return the value of form_qx_sjsh_sqs.PLAN_AGENT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getPlanAgent() {
        return planAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.PLAN_AGENT
     *
     * @param planAgent the value for form_qx_sjsh_sqs.PLAN_AGENT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setPlanAgent(String planAgent) {
        this.planAgent = planAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.PLAN_DATE
     *
     * @return the value of form_qx_sjsh_sqs.PLAN_DATE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public Date getPlanDate() {
        return planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.PLAN_DATE
     *
     * @param planDate the value for form_qx_sjsh_sqs.PLAN_DATE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.APPLY_UNIT
     *
     * @return the value of form_qx_sjsh_sqs.APPLY_UNIT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getApplyUnit() {
        return applyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.APPLY_UNIT
     *
     * @param applyUnit the value for form_qx_sjsh_sqs.APPLY_UNIT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setApplyUnit(String applyUnit) {
        this.applyUnit = applyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.APPLY_AGENT
     *
     * @return the value of form_qx_sjsh_sqs.APPLY_AGENT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public String getApplyAgent() {
        return applyAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.APPLY_AGENT
     *
     * @param applyAgent the value for form_qx_sjsh_sqs.APPLY_AGENT
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setApplyAgent(String applyAgent) {
        this.applyAgent = applyAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.APPLY_DATE
     *
     * @return the value of form_qx_sjsh_sqs.APPLY_DATE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.APPLY_DATE
     *
     * @param applyDate the value for form_qx_sjsh_sqs.APPLY_DATE
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjsh_sqs.APPLY_DATES
     *
     * @return the value of form_qx_sjsh_sqs.APPLY_DATES
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public Date getApplyDates() {
        return applyDates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjsh_sqs.APPLY_DATES
     *
     * @param applyDates the value for form_qx_sjsh_sqs.APPLY_DATES
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    public void setApplyDates(Date applyDates) {
        this.applyDates = applyDates;
    }
}