package com.lpcode.modules.blsp.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FormGtSqwtsFrdbzmsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    protected int start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public FormGtSqwtsFrdbzmsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setStart(int start) {
        this.start=start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public int getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("CREAT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("CREAT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterion("CREAT_TIME =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterion("CREAT_TIME <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterion("CREAT_TIME >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREAT_TIME >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterion("CREAT_TIME <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREAT_TIME <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterion("CREAT_TIME in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterion("CREAT_TIME not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterion("CREAT_TIME between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREAT_TIME not between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNull() {
            addCriterion("UPDATOR is null");
            return (Criteria) this;
        }

        public Criteria andUpdatorIsNotNull() {
            addCriterion("UPDATOR is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatorEqualTo(String value) {
            addCriterion("UPDATOR =", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotEqualTo(String value) {
            addCriterion("UPDATOR <>", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThan(String value) {
            addCriterion("UPDATOR >", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATOR >=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThan(String value) {
            addCriterion("UPDATOR <", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLessThanOrEqualTo(String value) {
            addCriterion("UPDATOR <=", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorLike(String value) {
            addCriterion("UPDATOR like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotLike(String value) {
            addCriterion("UPDATOR not like", value, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorIn(List<String> values) {
            addCriterion("UPDATOR in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotIn(List<String> values) {
            addCriterion("UPDATOR not in", values, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorBetween(String value1, String value2) {
            addCriterion("UPDATOR between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andUpdatorNotBetween(String value1, String value2) {
            addCriterion("UPDATOR not between", value1, value2, "updator");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(String value) {
            addCriterion("IS_DELETE =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(String value) {
            addCriterion("IS_DELETE <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(String value) {
            addCriterion("IS_DELETE >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETE >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(String value) {
            addCriterion("IS_DELETE <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETE <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLike(String value) {
            addCriterion("IS_DELETE like", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotLike(String value) {
            addCriterion("IS_DELETE not like", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<String> values) {
            addCriterion("IS_DELETE in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<String> values) {
            addCriterion("IS_DELETE not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(String value1, String value2) {
            addCriterion("IS_DELETE between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(String value1, String value2) {
            addCriterion("IS_DELETE not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andPrjIdIsNull() {
            addCriterion("PRJ_ID is null");
            return (Criteria) this;
        }

        public Criteria andPrjIdIsNotNull() {
            addCriterion("PRJ_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPrjIdEqualTo(Long value) {
            addCriterion("PRJ_ID =", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdNotEqualTo(Long value) {
            addCriterion("PRJ_ID <>", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdGreaterThan(Long value) {
            addCriterion("PRJ_ID >", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PRJ_ID >=", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdLessThan(Long value) {
            addCriterion("PRJ_ID <", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdLessThanOrEqualTo(Long value) {
            addCriterion("PRJ_ID <=", value, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdIn(List<Long> values) {
            addCriterion("PRJ_ID in", values, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdNotIn(List<Long> values) {
            addCriterion("PRJ_ID not in", values, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdBetween(Long value1, Long value2) {
            addCriterion("PRJ_ID between", value1, value2, "prjId");
            return (Criteria) this;
        }

        public Criteria andPrjIdNotBetween(Long value1, Long value2) {
            addCriterion("PRJ_ID not between", value1, value2, "prjId");
            return (Criteria) this;
        }

        public Criteria andBaileeIsNull() {
            addCriterion("BAILEE is null");
            return (Criteria) this;
        }

        public Criteria andBaileeIsNotNull() {
            addCriterion("BAILEE is not null");
            return (Criteria) this;
        }

        public Criteria andBaileeEqualTo(String value) {
            addCriterion("BAILEE =", value, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeNotEqualTo(String value) {
            addCriterion("BAILEE <>", value, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeGreaterThan(String value) {
            addCriterion("BAILEE >", value, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeGreaterThanOrEqualTo(String value) {
            addCriterion("BAILEE >=", value, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeLessThan(String value) {
            addCriterion("BAILEE <", value, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeLessThanOrEqualTo(String value) {
            addCriterion("BAILEE <=", value, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeLike(String value) {
            addCriterion("BAILEE like", value, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeNotLike(String value) {
            addCriterion("BAILEE not like", value, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeIn(List<String> values) {
            addCriterion("BAILEE in", values, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeNotIn(List<String> values) {
            addCriterion("BAILEE not in", values, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeBetween(String value1, String value2) {
            addCriterion("BAILEE between", value1, value2, "bailee");
            return (Criteria) this;
        }

        public Criteria andBaileeNotBetween(String value1, String value2) {
            addCriterion("BAILEE not between", value1, value2, "bailee");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("TASK_ID is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("TASK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Long value) {
            addCriterion("TASK_ID =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Long value) {
            addCriterion("TASK_ID <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Long value) {
            addCriterion("TASK_ID >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TASK_ID >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Long value) {
            addCriterion("TASK_ID <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Long value) {
            addCriterion("TASK_ID <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Long> values) {
            addCriterion("TASK_ID in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Long> values) {
            addCriterion("TASK_ID not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Long value1, Long value2) {
            addCriterion("TASK_ID between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Long value1, Long value2) {
            addCriterion("TASK_ID not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTasknameIsNull() {
            addCriterion("TASKNAME is null");
            return (Criteria) this;
        }

        public Criteria andTasknameIsNotNull() {
            addCriterion("TASKNAME is not null");
            return (Criteria) this;
        }

        public Criteria andTasknameEqualTo(String value) {
            addCriterion("TASKNAME =", value, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameNotEqualTo(String value) {
            addCriterion("TASKNAME <>", value, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameGreaterThan(String value) {
            addCriterion("TASKNAME >", value, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameGreaterThanOrEqualTo(String value) {
            addCriterion("TASKNAME >=", value, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameLessThan(String value) {
            addCriterion("TASKNAME <", value, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameLessThanOrEqualTo(String value) {
            addCriterion("TASKNAME <=", value, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameLike(String value) {
            addCriterion("TASKNAME like", value, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameNotLike(String value) {
            addCriterion("TASKNAME not like", value, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameIn(List<String> values) {
            addCriterion("TASKNAME in", values, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameNotIn(List<String> values) {
            addCriterion("TASKNAME not in", values, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameBetween(String value1, String value2) {
            addCriterion("TASKNAME between", value1, value2, "taskname");
            return (Criteria) this;
        }

        public Criteria andTasknameNotBetween(String value1, String value2) {
            addCriterion("TASKNAME not between", value1, value2, "taskname");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("STARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("STARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(Date value) {
            addCriterion("STARTDATE =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(Date value) {
            addCriterion("STARTDATE <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(Date value) {
            addCriterion("STARTDATE >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
            addCriterion("STARTDATE >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(Date value) {
            addCriterion("STARTDATE <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(Date value) {
            addCriterion("STARTDATE <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<Date> values) {
            addCriterion("STARTDATE in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<Date> values) {
            addCriterion("STARTDATE not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(Date value1, Date value2) {
            addCriterion("STARTDATE between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(Date value1, Date value2) {
            addCriterion("STARTDATE not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andBaiIdIsNull() {
            addCriterion("BAI_ID is null");
            return (Criteria) this;
        }

        public Criteria andBaiIdIsNotNull() {
            addCriterion("BAI_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBaiIdEqualTo(String value) {
            addCriterion("BAI_ID =", value, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdNotEqualTo(String value) {
            addCriterion("BAI_ID <>", value, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdGreaterThan(String value) {
            addCriterion("BAI_ID >", value, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdGreaterThanOrEqualTo(String value) {
            addCriterion("BAI_ID >=", value, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdLessThan(String value) {
            addCriterion("BAI_ID <", value, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdLessThanOrEqualTo(String value) {
            addCriterion("BAI_ID <=", value, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdLike(String value) {
            addCriterion("BAI_ID like", value, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdNotLike(String value) {
            addCriterion("BAI_ID not like", value, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdIn(List<String> values) {
            addCriterion("BAI_ID in", values, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdNotIn(List<String> values) {
            addCriterion("BAI_ID not in", values, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdBetween(String value1, String value2) {
            addCriterion("BAI_ID between", value1, value2, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiIdNotBetween(String value1, String value2) {
            addCriterion("BAI_ID not between", value1, value2, "baiId");
            return (Criteria) this;
        }

        public Criteria andBaiAddIsNull() {
            addCriterion("BAI_ADD is null");
            return (Criteria) this;
        }

        public Criteria andBaiAddIsNotNull() {
            addCriterion("BAI_ADD is not null");
            return (Criteria) this;
        }

        public Criteria andBaiAddEqualTo(String value) {
            addCriterion("BAI_ADD =", value, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddNotEqualTo(String value) {
            addCriterion("BAI_ADD <>", value, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddGreaterThan(String value) {
            addCriterion("BAI_ADD >", value, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddGreaterThanOrEqualTo(String value) {
            addCriterion("BAI_ADD >=", value, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddLessThan(String value) {
            addCriterion("BAI_ADD <", value, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddLessThanOrEqualTo(String value) {
            addCriterion("BAI_ADD <=", value, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddLike(String value) {
            addCriterion("BAI_ADD like", value, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddNotLike(String value) {
            addCriterion("BAI_ADD not like", value, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddIn(List<String> values) {
            addCriterion("BAI_ADD in", values, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddNotIn(List<String> values) {
            addCriterion("BAI_ADD not in", values, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddBetween(String value1, String value2) {
            addCriterion("BAI_ADD between", value1, value2, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiAddNotBetween(String value1, String value2) {
            addCriterion("BAI_ADD not between", value1, value2, "baiAdd");
            return (Criteria) this;
        }

        public Criteria andBaiTelIsNull() {
            addCriterion("BAI_TEL is null");
            return (Criteria) this;
        }

        public Criteria andBaiTelIsNotNull() {
            addCriterion("BAI_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andBaiTelEqualTo(String value) {
            addCriterion("BAI_TEL =", value, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelNotEqualTo(String value) {
            addCriterion("BAI_TEL <>", value, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelGreaterThan(String value) {
            addCriterion("BAI_TEL >", value, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelGreaterThanOrEqualTo(String value) {
            addCriterion("BAI_TEL >=", value, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelLessThan(String value) {
            addCriterion("BAI_TEL <", value, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelLessThanOrEqualTo(String value) {
            addCriterion("BAI_TEL <=", value, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelLike(String value) {
            addCriterion("BAI_TEL like", value, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelNotLike(String value) {
            addCriterion("BAI_TEL not like", value, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelIn(List<String> values) {
            addCriterion("BAI_TEL in", values, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelNotIn(List<String> values) {
            addCriterion("BAI_TEL not in", values, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelBetween(String value1, String value2) {
            addCriterion("BAI_TEL between", value1, value2, "baiTel");
            return (Criteria) this;
        }

        public Criteria andBaiTelNotBetween(String value1, String value2) {
            addCriterion("BAI_TEL not between", value1, value2, "baiTel");
            return (Criteria) this;
        }

        public Criteria andConsignorIsNull() {
            addCriterion("CONSIGNOR is null");
            return (Criteria) this;
        }

        public Criteria andConsignorIsNotNull() {
            addCriterion("CONSIGNOR is not null");
            return (Criteria) this;
        }

        public Criteria andConsignorEqualTo(String value) {
            addCriterion("CONSIGNOR =", value, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorNotEqualTo(String value) {
            addCriterion("CONSIGNOR <>", value, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorGreaterThan(String value) {
            addCriterion("CONSIGNOR >", value, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorGreaterThanOrEqualTo(String value) {
            addCriterion("CONSIGNOR >=", value, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorLessThan(String value) {
            addCriterion("CONSIGNOR <", value, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorLessThanOrEqualTo(String value) {
            addCriterion("CONSIGNOR <=", value, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorLike(String value) {
            addCriterion("CONSIGNOR like", value, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorNotLike(String value) {
            addCriterion("CONSIGNOR not like", value, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorIn(List<String> values) {
            addCriterion("CONSIGNOR in", values, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorNotIn(List<String> values) {
            addCriterion("CONSIGNOR not in", values, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorBetween(String value1, String value2) {
            addCriterion("CONSIGNOR between", value1, value2, "consignor");
            return (Criteria) this;
        }

        public Criteria andConsignorNotBetween(String value1, String value2) {
            addCriterion("CONSIGNOR not between", value1, value2, "consignor");
            return (Criteria) this;
        }

        public Criteria andConIdIsNull() {
            addCriterion("CON_ID is null");
            return (Criteria) this;
        }

        public Criteria andConIdIsNotNull() {
            addCriterion("CON_ID is not null");
            return (Criteria) this;
        }

        public Criteria andConIdEqualTo(String value) {
            addCriterion("CON_ID =", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotEqualTo(String value) {
            addCriterion("CON_ID <>", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdGreaterThan(String value) {
            addCriterion("CON_ID >", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdGreaterThanOrEqualTo(String value) {
            addCriterion("CON_ID >=", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdLessThan(String value) {
            addCriterion("CON_ID <", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdLessThanOrEqualTo(String value) {
            addCriterion("CON_ID <=", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdLike(String value) {
            addCriterion("CON_ID like", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotLike(String value) {
            addCriterion("CON_ID not like", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdIn(List<String> values) {
            addCriterion("CON_ID in", values, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotIn(List<String> values) {
            addCriterion("CON_ID not in", values, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdBetween(String value1, String value2) {
            addCriterion("CON_ID between", value1, value2, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotBetween(String value1, String value2) {
            addCriterion("CON_ID not between", value1, value2, "conId");
            return (Criteria) this;
        }

        public Criteria andConTelIsNull() {
            addCriterion("CON_TEL is null");
            return (Criteria) this;
        }

        public Criteria andConTelIsNotNull() {
            addCriterion("CON_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andConTelEqualTo(String value) {
            addCriterion("CON_TEL =", value, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelNotEqualTo(String value) {
            addCriterion("CON_TEL <>", value, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelGreaterThan(String value) {
            addCriterion("CON_TEL >", value, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelGreaterThanOrEqualTo(String value) {
            addCriterion("CON_TEL >=", value, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelLessThan(String value) {
            addCriterion("CON_TEL <", value, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelLessThanOrEqualTo(String value) {
            addCriterion("CON_TEL <=", value, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelLike(String value) {
            addCriterion("CON_TEL like", value, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelNotLike(String value) {
            addCriterion("CON_TEL not like", value, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelIn(List<String> values) {
            addCriterion("CON_TEL in", values, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelNotIn(List<String> values) {
            addCriterion("CON_TEL not in", values, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelBetween(String value1, String value2) {
            addCriterion("CON_TEL between", value1, value2, "conTel");
            return (Criteria) this;
        }

        public Criteria andConTelNotBetween(String value1, String value2) {
            addCriterion("CON_TEL not between", value1, value2, "conTel");
            return (Criteria) this;
        }

        public Criteria andConDateIsNull() {
            addCriterion("CON_DATE is null");
            return (Criteria) this;
        }

        public Criteria andConDateIsNotNull() {
            addCriterion("CON_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andConDateEqualTo(Date value) {
            addCriterion("CON_DATE =", value, "conDate");
            return (Criteria) this;
        }

        public Criteria andConDateNotEqualTo(Date value) {
            addCriterion("CON_DATE <>", value, "conDate");
            return (Criteria) this;
        }

        public Criteria andConDateGreaterThan(Date value) {
            addCriterion("CON_DATE >", value, "conDate");
            return (Criteria) this;
        }

        public Criteria andConDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CON_DATE >=", value, "conDate");
            return (Criteria) this;
        }

        public Criteria andConDateLessThan(Date value) {
            addCriterion("CON_DATE <", value, "conDate");
            return (Criteria) this;
        }

        public Criteria andConDateLessThanOrEqualTo(Date value) {
            addCriterion("CON_DATE <=", value, "conDate");
            return (Criteria) this;
        }

        public Criteria andConDateIn(List<Date> values) {
            addCriterion("CON_DATE in", values, "conDate");
            return (Criteria) this;
        }

        public Criteria andConDateNotIn(List<Date> values) {
            addCriterion("CON_DATE not in", values, "conDate");
            return (Criteria) this;
        }

        public Criteria andConDateBetween(Date value1, Date value2) {
            addCriterion("CON_DATE between", value1, value2, "conDate");
            return (Criteria) this;
        }

        public Criteria andConDateNotBetween(Date value1, Date value2) {
            addCriterion("CON_DATE not between", value1, value2, "conDate");
            return (Criteria) this;
        }

        public Criteria andLeaglIsNull() {
            addCriterion("LEAGL is null");
            return (Criteria) this;
        }

        public Criteria andLeaglIsNotNull() {
            addCriterion("LEAGL is not null");
            return (Criteria) this;
        }

        public Criteria andLeaglEqualTo(String value) {
            addCriterion("LEAGL =", value, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglNotEqualTo(String value) {
            addCriterion("LEAGL <>", value, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglGreaterThan(String value) {
            addCriterion("LEAGL >", value, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglGreaterThanOrEqualTo(String value) {
            addCriterion("LEAGL >=", value, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglLessThan(String value) {
            addCriterion("LEAGL <", value, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglLessThanOrEqualTo(String value) {
            addCriterion("LEAGL <=", value, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglLike(String value) {
            addCriterion("LEAGL like", value, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglNotLike(String value) {
            addCriterion("LEAGL not like", value, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglIn(List<String> values) {
            addCriterion("LEAGL in", values, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglNotIn(List<String> values) {
            addCriterion("LEAGL not in", values, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglBetween(String value1, String value2) {
            addCriterion("LEAGL between", value1, value2, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaglNotBetween(String value1, String value2) {
            addCriterion("LEAGL not between", value1, value2, "leagl");
            return (Criteria) this;
        }

        public Criteria andLeaDutyIsNull() {
            addCriterion("LEA_DUTY is null");
            return (Criteria) this;
        }

        public Criteria andLeaDutyIsNotNull() {
            addCriterion("LEA_DUTY is not null");
            return (Criteria) this;
        }

        public Criteria andLeaDutyEqualTo(String value) {
            addCriterion("LEA_DUTY =", value, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyNotEqualTo(String value) {
            addCriterion("LEA_DUTY <>", value, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyGreaterThan(String value) {
            addCriterion("LEA_DUTY >", value, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyGreaterThanOrEqualTo(String value) {
            addCriterion("LEA_DUTY >=", value, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyLessThan(String value) {
            addCriterion("LEA_DUTY <", value, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyLessThanOrEqualTo(String value) {
            addCriterion("LEA_DUTY <=", value, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyLike(String value) {
            addCriterion("LEA_DUTY like", value, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyNotLike(String value) {
            addCriterion("LEA_DUTY not like", value, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyIn(List<String> values) {
            addCriterion("LEA_DUTY in", values, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyNotIn(List<String> values) {
            addCriterion("LEA_DUTY not in", values, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyBetween(String value1, String value2) {
            addCriterion("LEA_DUTY between", value1, value2, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andLeaDutyNotBetween(String value1, String value2) {
            addCriterion("LEA_DUTY not between", value1, value2, "leaDuty");
            return (Criteria) this;
        }

        public Criteria andNatureIsNull() {
            addCriterion("NATURE is null");
            return (Criteria) this;
        }

        public Criteria andNatureIsNotNull() {
            addCriterion("NATURE is not null");
            return (Criteria) this;
        }

        public Criteria andNatureEqualTo(String value) {
            addCriterion("NATURE =", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotEqualTo(String value) {
            addCriterion("NATURE <>", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureGreaterThan(String value) {
            addCriterion("NATURE >", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureGreaterThanOrEqualTo(String value) {
            addCriterion("NATURE >=", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureLessThan(String value) {
            addCriterion("NATURE <", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureLessThanOrEqualTo(String value) {
            addCriterion("NATURE <=", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureLike(String value) {
            addCriterion("NATURE like", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotLike(String value) {
            addCriterion("NATURE not like", value, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureIn(List<String> values) {
            addCriterion("NATURE in", values, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotIn(List<String> values) {
            addCriterion("NATURE not in", values, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureBetween(String value1, String value2) {
            addCriterion("NATURE between", value1, value2, "nature");
            return (Criteria) this;
        }

        public Criteria andNatureNotBetween(String value1, String value2) {
            addCriterion("NATURE not between", value1, value2, "nature");
            return (Criteria) this;
        }

        public Criteria andBusLicIdIsNull() {
            addCriterion("BUS_LIC_ID is null");
            return (Criteria) this;
        }

        public Criteria andBusLicIdIsNotNull() {
            addCriterion("BUS_LIC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBusLicIdEqualTo(String value) {
            addCriterion("BUS_LIC_ID =", value, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdNotEqualTo(String value) {
            addCriterion("BUS_LIC_ID <>", value, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdGreaterThan(String value) {
            addCriterion("BUS_LIC_ID >", value, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdGreaterThanOrEqualTo(String value) {
            addCriterion("BUS_LIC_ID >=", value, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdLessThan(String value) {
            addCriterion("BUS_LIC_ID <", value, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdLessThanOrEqualTo(String value) {
            addCriterion("BUS_LIC_ID <=", value, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdLike(String value) {
            addCriterion("BUS_LIC_ID like", value, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdNotLike(String value) {
            addCriterion("BUS_LIC_ID not like", value, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdIn(List<String> values) {
            addCriterion("BUS_LIC_ID in", values, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdNotIn(List<String> values) {
            addCriterion("BUS_LIC_ID not in", values, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdBetween(String value1, String value2) {
            addCriterion("BUS_LIC_ID between", value1, value2, "busLicId");
            return (Criteria) this;
        }

        public Criteria andBusLicIdNotBetween(String value1, String value2) {
            addCriterion("BUS_LIC_ID not between", value1, value2, "busLicId");
            return (Criteria) this;
        }

        public Criteria andUnitTelIsNull() {
            addCriterion("UNIT_TEL is null");
            return (Criteria) this;
        }

        public Criteria andUnitTelIsNotNull() {
            addCriterion("UNIT_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andUnitTelEqualTo(String value) {
            addCriterion("UNIT_TEL =", value, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelNotEqualTo(String value) {
            addCriterion("UNIT_TEL <>", value, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelGreaterThan(String value) {
            addCriterion("UNIT_TEL >", value, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT_TEL >=", value, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelLessThan(String value) {
            addCriterion("UNIT_TEL <", value, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelLessThanOrEqualTo(String value) {
            addCriterion("UNIT_TEL <=", value, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelLike(String value) {
            addCriterion("UNIT_TEL like", value, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelNotLike(String value) {
            addCriterion("UNIT_TEL not like", value, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelIn(List<String> values) {
            addCriterion("UNIT_TEL in", values, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelNotIn(List<String> values) {
            addCriterion("UNIT_TEL not in", values, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelBetween(String value1, String value2) {
            addCriterion("UNIT_TEL between", value1, value2, "unitTel");
            return (Criteria) this;
        }

        public Criteria andUnitTelNotBetween(String value1, String value2) {
            addCriterion("UNIT_TEL not between", value1, value2, "unitTel");
            return (Criteria) this;
        }

        public Criteria andLeaIdIsNull() {
            addCriterion("LEA_ID is null");
            return (Criteria) this;
        }

        public Criteria andLeaIdIsNotNull() {
            addCriterion("LEA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLeaIdEqualTo(String value) {
            addCriterion("LEA_ID =", value, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdNotEqualTo(String value) {
            addCriterion("LEA_ID <>", value, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdGreaterThan(String value) {
            addCriterion("LEA_ID >", value, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdGreaterThanOrEqualTo(String value) {
            addCriterion("LEA_ID >=", value, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdLessThan(String value) {
            addCriterion("LEA_ID <", value, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdLessThanOrEqualTo(String value) {
            addCriterion("LEA_ID <=", value, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdLike(String value) {
            addCriterion("LEA_ID like", value, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdNotLike(String value) {
            addCriterion("LEA_ID not like", value, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdIn(List<String> values) {
            addCriterion("LEA_ID in", values, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdNotIn(List<String> values) {
            addCriterion("LEA_ID not in", values, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdBetween(String value1, String value2) {
            addCriterion("LEA_ID between", value1, value2, "leaId");
            return (Criteria) this;
        }

        public Criteria andLeaIdNotBetween(String value1, String value2) {
            addCriterion("LEA_ID not between", value1, value2, "leaId");
            return (Criteria) this;
        }

        public Criteria andSignDateIsNull() {
            addCriterion("SIGN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSignDateIsNotNull() {
            addCriterion("SIGN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSignDateEqualTo(Date value) {
            addCriterion("SIGN_DATE =", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateNotEqualTo(Date value) {
            addCriterion("SIGN_DATE <>", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateGreaterThan(Date value) {
            addCriterion("SIGN_DATE >", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateGreaterThanOrEqualTo(Date value) {
            addCriterion("SIGN_DATE >=", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateLessThan(Date value) {
            addCriterion("SIGN_DATE <", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateLessThanOrEqualTo(Date value) {
            addCriterion("SIGN_DATE <=", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateIn(List<Date> values) {
            addCriterion("SIGN_DATE in", values, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateNotIn(List<Date> values) {
            addCriterion("SIGN_DATE not in", values, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateBetween(Date value1, Date value2) {
            addCriterion("SIGN_DATE between", value1, value2, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateNotBetween(Date value1, Date value2) {
            addCriterion("SIGN_DATE not between", value1, value2, "signDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 20 14:23:30 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table form_gt_sqwts_frdbzms
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}