package com.lpcode.modules.blsp.entity;

import java.util.Date;

public class FormHbJsxmJjxm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.ID
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.CREAT_TIME
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.CREATOR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.UPDATE_TIME
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.UPDATOR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.IS_DELETE
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.PRJ_ID
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private Long prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.TASK_ID
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.PRJ_NAME
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String prjName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.COMPANY
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.APPLY_DATE
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private Date applyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.PRJ_ADDR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String prjAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.APP_CON_ADDR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String appConAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.APPLY_CON_TEL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String applyConTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.ADD_MATERIAL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String addMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.ADD_OTHER
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String addOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.PRJ_PRINCIPAL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String prjPrincipal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.TOTAL_INVEST
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String totalInvest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.APPROVAL_NUM
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String approvalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.PLAN_APPROVAL_NUM
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String planApprovalNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.FLOOR_AREA
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String floorArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.PLIES_NUM
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String pliesNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.TOTAL_BUILD_AREA
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String totalBuildArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.USE_FUNCTION
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String useFunction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.NEED_EXPLAIN
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String needExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.OPERATOR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_hb_jsxm_jjxm.OPER_TEL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    private String operTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.ID
     *
     * @return the value of form_hb_jsxm_jjxm.ID
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.ID
     *
     * @param id the value for form_hb_jsxm_jjxm.ID
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.CREAT_TIME
     *
     * @return the value of form_hb_jsxm_jjxm.CREAT_TIME
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.CREAT_TIME
     *
     * @param creatTime the value for form_hb_jsxm_jjxm.CREAT_TIME
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.CREATOR
     *
     * @return the value of form_hb_jsxm_jjxm.CREATOR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.CREATOR
     *
     * @param creator the value for form_hb_jsxm_jjxm.CREATOR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.UPDATE_TIME
     *
     * @return the value of form_hb_jsxm_jjxm.UPDATE_TIME
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.UPDATE_TIME
     *
     * @param updateTime the value for form_hb_jsxm_jjxm.UPDATE_TIME
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.UPDATOR
     *
     * @return the value of form_hb_jsxm_jjxm.UPDATOR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.UPDATOR
     *
     * @param updator the value for form_hb_jsxm_jjxm.UPDATOR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.IS_DELETE
     *
     * @return the value of form_hb_jsxm_jjxm.IS_DELETE
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.IS_DELETE
     *
     * @param isDelete the value for form_hb_jsxm_jjxm.IS_DELETE
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.PRJ_ID
     *
     * @return the value of form_hb_jsxm_jjxm.PRJ_ID
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public Long getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.PRJ_ID
     *
     * @param prjId the value for form_hb_jsxm_jjxm.PRJ_ID
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setPrjId(Long prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.TASK_ID
     *
     * @return the value of form_hb_jsxm_jjxm.TASK_ID
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.TASK_ID
     *
     * @param taskId the value for form_hb_jsxm_jjxm.TASK_ID
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.PRJ_NAME
     *
     * @return the value of form_hb_jsxm_jjxm.PRJ_NAME
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getPrjName() {
        return prjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.PRJ_NAME
     *
     * @param prjName the value for form_hb_jsxm_jjxm.PRJ_NAME
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setPrjName(String prjName) {
        this.prjName = prjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.COMPANY
     *
     * @return the value of form_hb_jsxm_jjxm.COMPANY
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.COMPANY
     *
     * @param company the value for form_hb_jsxm_jjxm.COMPANY
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.APPLY_DATE
     *
     * @return the value of form_hb_jsxm_jjxm.APPLY_DATE
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.APPLY_DATE
     *
     * @param applyDate the value for form_hb_jsxm_jjxm.APPLY_DATE
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.PRJ_ADDR
     *
     * @return the value of form_hb_jsxm_jjxm.PRJ_ADDR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getPrjAddr() {
        return prjAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.PRJ_ADDR
     *
     * @param prjAddr the value for form_hb_jsxm_jjxm.PRJ_ADDR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setPrjAddr(String prjAddr) {
        this.prjAddr = prjAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.APP_CON_ADDR
     *
     * @return the value of form_hb_jsxm_jjxm.APP_CON_ADDR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getAppConAddr() {
        return appConAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.APP_CON_ADDR
     *
     * @param appConAddr the value for form_hb_jsxm_jjxm.APP_CON_ADDR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setAppConAddr(String appConAddr) {
        this.appConAddr = appConAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.APPLY_CON_TEL
     *
     * @return the value of form_hb_jsxm_jjxm.APPLY_CON_TEL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getApplyConTel() {
        return applyConTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.APPLY_CON_TEL
     *
     * @param applyConTel the value for form_hb_jsxm_jjxm.APPLY_CON_TEL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setApplyConTel(String applyConTel) {
        this.applyConTel = applyConTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.ADD_MATERIAL
     *
     * @return the value of form_hb_jsxm_jjxm.ADD_MATERIAL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getAddMaterial() {
        return addMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.ADD_MATERIAL
     *
     * @param addMaterial the value for form_hb_jsxm_jjxm.ADD_MATERIAL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setAddMaterial(String addMaterial) {
        this.addMaterial = addMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.ADD_OTHER
     *
     * @return the value of form_hb_jsxm_jjxm.ADD_OTHER
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getAddOther() {
        return addOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.ADD_OTHER
     *
     * @param addOther the value for form_hb_jsxm_jjxm.ADD_OTHER
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setAddOther(String addOther) {
        this.addOther = addOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.PRJ_PRINCIPAL
     *
     * @return the value of form_hb_jsxm_jjxm.PRJ_PRINCIPAL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getPrjPrincipal() {
        return prjPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.PRJ_PRINCIPAL
     *
     * @param prjPrincipal the value for form_hb_jsxm_jjxm.PRJ_PRINCIPAL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setPrjPrincipal(String prjPrincipal) {
        this.prjPrincipal = prjPrincipal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.TOTAL_INVEST
     *
     * @return the value of form_hb_jsxm_jjxm.TOTAL_INVEST
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getTotalInvest() {
        return totalInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.TOTAL_INVEST
     *
     * @param totalInvest the value for form_hb_jsxm_jjxm.TOTAL_INVEST
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setTotalInvest(String totalInvest) {
        this.totalInvest = totalInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.APPROVAL_NUM
     *
     * @return the value of form_hb_jsxm_jjxm.APPROVAL_NUM
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getApprovalNum() {
        return approvalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.APPROVAL_NUM
     *
     * @param approvalNum the value for form_hb_jsxm_jjxm.APPROVAL_NUM
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setApprovalNum(String approvalNum) {
        this.approvalNum = approvalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.PLAN_APPROVAL_NUM
     *
     * @return the value of form_hb_jsxm_jjxm.PLAN_APPROVAL_NUM
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getPlanApprovalNum() {
        return planApprovalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.PLAN_APPROVAL_NUM
     *
     * @param planApprovalNum the value for form_hb_jsxm_jjxm.PLAN_APPROVAL_NUM
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setPlanApprovalNum(String planApprovalNum) {
        this.planApprovalNum = planApprovalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.FLOOR_AREA
     *
     * @return the value of form_hb_jsxm_jjxm.FLOOR_AREA
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getFloorArea() {
        return floorArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.FLOOR_AREA
     *
     * @param floorArea the value for form_hb_jsxm_jjxm.FLOOR_AREA
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setFloorArea(String floorArea) {
        this.floorArea = floorArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.PLIES_NUM
     *
     * @return the value of form_hb_jsxm_jjxm.PLIES_NUM
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getPliesNum() {
        return pliesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.PLIES_NUM
     *
     * @param pliesNum the value for form_hb_jsxm_jjxm.PLIES_NUM
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setPliesNum(String pliesNum) {
        this.pliesNum = pliesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.TOTAL_BUILD_AREA
     *
     * @return the value of form_hb_jsxm_jjxm.TOTAL_BUILD_AREA
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getTotalBuildArea() {
        return totalBuildArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.TOTAL_BUILD_AREA
     *
     * @param totalBuildArea the value for form_hb_jsxm_jjxm.TOTAL_BUILD_AREA
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setTotalBuildArea(String totalBuildArea) {
        this.totalBuildArea = totalBuildArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.USE_FUNCTION
     *
     * @return the value of form_hb_jsxm_jjxm.USE_FUNCTION
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getUseFunction() {
        return useFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.USE_FUNCTION
     *
     * @param useFunction the value for form_hb_jsxm_jjxm.USE_FUNCTION
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setUseFunction(String useFunction) {
        this.useFunction = useFunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.NEED_EXPLAIN
     *
     * @return the value of form_hb_jsxm_jjxm.NEED_EXPLAIN
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getNeedExplain() {
        return needExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.NEED_EXPLAIN
     *
     * @param needExplain the value for form_hb_jsxm_jjxm.NEED_EXPLAIN
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setNeedExplain(String needExplain) {
        this.needExplain = needExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.OPERATOR
     *
     * @return the value of form_hb_jsxm_jjxm.OPERATOR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.OPERATOR
     *
     * @param operator the value for form_hb_jsxm_jjxm.OPERATOR
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_hb_jsxm_jjxm.OPER_TEL
     *
     * @return the value of form_hb_jsxm_jjxm.OPER_TEL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public String getOperTel() {
        return operTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_hb_jsxm_jjxm.OPER_TEL
     *
     * @param operTel the value for form_hb_jsxm_jjxm.OPER_TEL
     *
     * @mbggenerated Wed Jul 13 14:32:28 CST 2016
     */
    public void setOperTel(String operTel) {
        this.operTel = operTel;
    }
}