package com.lpcode.modules.blsp.entity;

import java.util.Date;

public class FormDefine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_define.ID
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_define.FORM_NAME
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    private String formName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_define.FORM_CODE
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    private String formCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_define.FORM_DESC
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    private String formDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_define.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_define.CREATOR
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_define.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_define.UPDATOR
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_define.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_define.ID
     *
     * @return the value of form_define.ID
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_define.ID
     *
     * @param id the value for form_define.ID
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_define.FORM_NAME
     *
     * @return the value of form_define.FORM_NAME
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public String getFormName() {
        return formName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_define.FORM_NAME
     *
     * @param formName the value for form_define.FORM_NAME
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setFormName(String formName) {
        this.formName = formName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_define.FORM_CODE
     *
     * @return the value of form_define.FORM_CODE
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public String getFormCode() {
        return formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_define.FORM_CODE
     *
     * @param formCode the value for form_define.FORM_CODE
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setFormCode(String formCode) {
        this.formCode = formCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_define.FORM_DESC
     *
     * @return the value of form_define.FORM_DESC
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public String getFormDesc() {
        return formDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_define.FORM_DESC
     *
     * @param formDesc the value for form_define.FORM_DESC
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setFormDesc(String formDesc) {
        this.formDesc = formDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_define.CREAT_TIME
     *
     * @return the value of form_define.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_define.CREAT_TIME
     *
     * @param creatTime the value for form_define.CREAT_TIME
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_define.CREATOR
     *
     * @return the value of form_define.CREATOR
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_define.CREATOR
     *
     * @param creator the value for form_define.CREATOR
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_define.UPDATE_TIME
     *
     * @return the value of form_define.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_define.UPDATE_TIME
     *
     * @param updateTime the value for form_define.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_define.UPDATOR
     *
     * @return the value of form_define.UPDATOR
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_define.UPDATOR
     *
     * @param updator the value for form_define.UPDATOR
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_define.IS_DELETE
     *
     * @return the value of form_define.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_define.IS_DELETE
     *
     * @param isDelete the value for form_define.IS_DELETE
     *
     * @mbggenerated Mon Jun 20 14:23:30 CST 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
}