package com.lpcode.modules.blsp.entity;

public class FormZjSgxkSqbSg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_zj_sgxk_sqb_sg.C_ID
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    private Long cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_zj_sgxk_sqb_sg.Z_ID
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    private Long zId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_zj_sgxk_sqb_sg.C_IS_DELETE
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    private String cIsDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_zj_sgxk_sqb_sg.C_UNIT_NAME
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    private String cUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_zj_sgxk_sqb_sg.C_SUB_MAJOR
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    private String cSubMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_zj_sgxk_sqb_sg.C_COST
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    private String cCost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_zj_sgxk_sqb_sg.C_ID
     *
     * @return the value of form_zj_sgxk_sqb_sg.C_ID
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_zj_sgxk_sqb_sg.C_ID
     *
     * @param cId the value for form_zj_sgxk_sqb_sg.C_ID
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_zj_sgxk_sqb_sg.Z_ID
     *
     * @return the value of form_zj_sgxk_sqb_sg.Z_ID
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public Long getzId() {
        return zId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_zj_sgxk_sqb_sg.Z_ID
     *
     * @param zId the value for form_zj_sgxk_sqb_sg.Z_ID
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void setzId(Long zId) {
        this.zId = zId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_zj_sgxk_sqb_sg.C_IS_DELETE
     *
     * @return the value of form_zj_sgxk_sqb_sg.C_IS_DELETE
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public String getcIsDelete() {
        return cIsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_zj_sgxk_sqb_sg.C_IS_DELETE
     *
     * @param cIsDelete the value for form_zj_sgxk_sqb_sg.C_IS_DELETE
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void setcIsDelete(String cIsDelete) {
        this.cIsDelete = cIsDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_zj_sgxk_sqb_sg.C_UNIT_NAME
     *
     * @return the value of form_zj_sgxk_sqb_sg.C_UNIT_NAME
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public String getcUnitName() {
        return cUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_zj_sgxk_sqb_sg.C_UNIT_NAME
     *
     * @param cUnitName the value for form_zj_sgxk_sqb_sg.C_UNIT_NAME
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void setcUnitName(String cUnitName) {
        this.cUnitName = cUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_zj_sgxk_sqb_sg.C_SUB_MAJOR
     *
     * @return the value of form_zj_sgxk_sqb_sg.C_SUB_MAJOR
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public String getcSubMajor() {
        return cSubMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_zj_sgxk_sqb_sg.C_SUB_MAJOR
     *
     * @param cSubMajor the value for form_zj_sgxk_sqb_sg.C_SUB_MAJOR
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void setcSubMajor(String cSubMajor) {
        this.cSubMajor = cSubMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_zj_sgxk_sqb_sg.C_COST
     *
     * @return the value of form_zj_sgxk_sqb_sg.C_COST
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public String getcCost() {
        return cCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_zj_sgxk_sqb_sg.C_COST
     *
     * @param cCost the value for form_zj_sgxk_sqb_sg.C_COST
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    public void setcCost(String cCost) {
        this.cCost = cCost;
    }
}