package com.lpcode.modules.blsp.entity;

import java.util.Date;

public class FormQxSjjsPjxx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.ID
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.CREAT_TIME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.CREATOR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.UPDATOR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.IS_DELETE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.PRJ_ID
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private Long prjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.TASK_ID
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.CONSTRUCTION_NAME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String constructionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.CONSTRUCTION_ADDR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String constructionAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.CONSTRUCTION_LINKMAN
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String constructionLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.CONSTRUCTION_LINKTEL
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String constructionLinktel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.DESIGN_NAME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String designName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.DESIGN_LINKMAN
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String designLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.DESIGN_LINKTEL
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String designLinktel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.PRJ_NAME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String prjName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.PRJ_ADDR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String prjAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.PLAN_LESENCE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String planLesence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.ON_FLOORS
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String onFloors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.ON_FLOORS_SPACE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String onFloorsSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.DOWN_FLOORS
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String downFloors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.DOWN_FLOORS_SPACE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String downFloorsSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.RIDGEPOLE_NUM
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String ridgepoleNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.FLOORS
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String floors;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.LINKMAN
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_qx_sjjs_pjxx.LINKTEL
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    private String linktel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.ID
     *
     * @return the value of form_qx_sjjs_pjxx.ID
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.ID
     *
     * @param id the value for form_qx_sjjs_pjxx.ID
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.CREAT_TIME
     *
     * @return the value of form_qx_sjjs_pjxx.CREAT_TIME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.CREAT_TIME
     *
     * @param creatTime the value for form_qx_sjjs_pjxx.CREAT_TIME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.CREATOR
     *
     * @return the value of form_qx_sjjs_pjxx.CREATOR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.CREATOR
     *
     * @param creator the value for form_qx_sjjs_pjxx.CREATOR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.UPDATE_TIME
     *
     * @return the value of form_qx_sjjs_pjxx.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.UPDATE_TIME
     *
     * @param updateTime the value for form_qx_sjjs_pjxx.UPDATE_TIME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.UPDATOR
     *
     * @return the value of form_qx_sjjs_pjxx.UPDATOR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.UPDATOR
     *
     * @param updator the value for form_qx_sjjs_pjxx.UPDATOR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setUpdator(String updator) {
        this.updator = updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.IS_DELETE
     *
     * @return the value of form_qx_sjjs_pjxx.IS_DELETE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.IS_DELETE
     *
     * @param isDelete the value for form_qx_sjjs_pjxx.IS_DELETE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.PRJ_ID
     *
     * @return the value of form_qx_sjjs_pjxx.PRJ_ID
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public Long getPrjId() {
        return prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.PRJ_ID
     *
     * @param prjId the value for form_qx_sjjs_pjxx.PRJ_ID
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setPrjId(Long prjId) {
        this.prjId = prjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.TASK_ID
     *
     * @return the value of form_qx_sjjs_pjxx.TASK_ID
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.TASK_ID
     *
     * @param taskId the value for form_qx_sjjs_pjxx.TASK_ID
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.CONSTRUCTION_NAME
     *
     * @return the value of form_qx_sjjs_pjxx.CONSTRUCTION_NAME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getConstructionName() {
        return constructionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.CONSTRUCTION_NAME
     *
     * @param constructionName the value for form_qx_sjjs_pjxx.CONSTRUCTION_NAME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setConstructionName(String constructionName) {
        this.constructionName = constructionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.CONSTRUCTION_ADDR
     *
     * @return the value of form_qx_sjjs_pjxx.CONSTRUCTION_ADDR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getConstructionAddr() {
        return constructionAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.CONSTRUCTION_ADDR
     *
     * @param constructionAddr the value for form_qx_sjjs_pjxx.CONSTRUCTION_ADDR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setConstructionAddr(String constructionAddr) {
        this.constructionAddr = constructionAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.CONSTRUCTION_LINKMAN
     *
     * @return the value of form_qx_sjjs_pjxx.CONSTRUCTION_LINKMAN
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getConstructionLinkman() {
        return constructionLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.CONSTRUCTION_LINKMAN
     *
     * @param constructionLinkman the value for form_qx_sjjs_pjxx.CONSTRUCTION_LINKMAN
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setConstructionLinkman(String constructionLinkman) {
        this.constructionLinkman = constructionLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.CONSTRUCTION_LINKTEL
     *
     * @return the value of form_qx_sjjs_pjxx.CONSTRUCTION_LINKTEL
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getConstructionLinktel() {
        return constructionLinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.CONSTRUCTION_LINKTEL
     *
     * @param constructionLinktel the value for form_qx_sjjs_pjxx.CONSTRUCTION_LINKTEL
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setConstructionLinktel(String constructionLinktel) {
        this.constructionLinktel = constructionLinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.DESIGN_NAME
     *
     * @return the value of form_qx_sjjs_pjxx.DESIGN_NAME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getDesignName() {
        return designName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.DESIGN_NAME
     *
     * @param designName the value for form_qx_sjjs_pjxx.DESIGN_NAME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setDesignName(String designName) {
        this.designName = designName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.DESIGN_LINKMAN
     *
     * @return the value of form_qx_sjjs_pjxx.DESIGN_LINKMAN
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getDesignLinkman() {
        return designLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.DESIGN_LINKMAN
     *
     * @param designLinkman the value for form_qx_sjjs_pjxx.DESIGN_LINKMAN
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setDesignLinkman(String designLinkman) {
        this.designLinkman = designLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.DESIGN_LINKTEL
     *
     * @return the value of form_qx_sjjs_pjxx.DESIGN_LINKTEL
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getDesignLinktel() {
        return designLinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.DESIGN_LINKTEL
     *
     * @param designLinktel the value for form_qx_sjjs_pjxx.DESIGN_LINKTEL
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setDesignLinktel(String designLinktel) {
        this.designLinktel = designLinktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.PRJ_NAME
     *
     * @return the value of form_qx_sjjs_pjxx.PRJ_NAME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getPrjName() {
        return prjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.PRJ_NAME
     *
     * @param prjName the value for form_qx_sjjs_pjxx.PRJ_NAME
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setPrjName(String prjName) {
        this.prjName = prjName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.PRJ_ADDR
     *
     * @return the value of form_qx_sjjs_pjxx.PRJ_ADDR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getPrjAddr() {
        return prjAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.PRJ_ADDR
     *
     * @param prjAddr the value for form_qx_sjjs_pjxx.PRJ_ADDR
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setPrjAddr(String prjAddr) {
        this.prjAddr = prjAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.PLAN_LESENCE
     *
     * @return the value of form_qx_sjjs_pjxx.PLAN_LESENCE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getPlanLesence() {
        return planLesence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.PLAN_LESENCE
     *
     * @param planLesence the value for form_qx_sjjs_pjxx.PLAN_LESENCE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setPlanLesence(String planLesence) {
        this.planLesence = planLesence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.ON_FLOORS
     *
     * @return the value of form_qx_sjjs_pjxx.ON_FLOORS
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getOnFloors() {
        return onFloors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.ON_FLOORS
     *
     * @param onFloors the value for form_qx_sjjs_pjxx.ON_FLOORS
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setOnFloors(String onFloors) {
        this.onFloors = onFloors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.ON_FLOORS_SPACE
     *
     * @return the value of form_qx_sjjs_pjxx.ON_FLOORS_SPACE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getOnFloorsSpace() {
        return onFloorsSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.ON_FLOORS_SPACE
     *
     * @param onFloorsSpace the value for form_qx_sjjs_pjxx.ON_FLOORS_SPACE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setOnFloorsSpace(String onFloorsSpace) {
        this.onFloorsSpace = onFloorsSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.DOWN_FLOORS
     *
     * @return the value of form_qx_sjjs_pjxx.DOWN_FLOORS
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getDownFloors() {
        return downFloors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.DOWN_FLOORS
     *
     * @param downFloors the value for form_qx_sjjs_pjxx.DOWN_FLOORS
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setDownFloors(String downFloors) {
        this.downFloors = downFloors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.DOWN_FLOORS_SPACE
     *
     * @return the value of form_qx_sjjs_pjxx.DOWN_FLOORS_SPACE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getDownFloorsSpace() {
        return downFloorsSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.DOWN_FLOORS_SPACE
     *
     * @param downFloorsSpace the value for form_qx_sjjs_pjxx.DOWN_FLOORS_SPACE
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setDownFloorsSpace(String downFloorsSpace) {
        this.downFloorsSpace = downFloorsSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.RIDGEPOLE_NUM
     *
     * @return the value of form_qx_sjjs_pjxx.RIDGEPOLE_NUM
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getRidgepoleNum() {
        return ridgepoleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.RIDGEPOLE_NUM
     *
     * @param ridgepoleNum the value for form_qx_sjjs_pjxx.RIDGEPOLE_NUM
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setRidgepoleNum(String ridgepoleNum) {
        this.ridgepoleNum = ridgepoleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.FLOORS
     *
     * @return the value of form_qx_sjjs_pjxx.FLOORS
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getFloors() {
        return floors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.FLOORS
     *
     * @param floors the value for form_qx_sjjs_pjxx.FLOORS
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setFloors(String floors) {
        this.floors = floors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.LINKMAN
     *
     * @return the value of form_qx_sjjs_pjxx.LINKMAN
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.LINKMAN
     *
     * @param linkman the value for form_qx_sjjs_pjxx.LINKMAN
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_qx_sjjs_pjxx.LINKTEL
     *
     * @return the value of form_qx_sjjs_pjxx.LINKTEL
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public String getLinktel() {
        return linktel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_qx_sjjs_pjxx.LINKTEL
     *
     * @param linktel the value for form_qx_sjjs_pjxx.LINKTEL
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    public void setLinktel(String linktel) {
        this.linktel = linktel;
    }
}