package com.lpcode.modules.blsp.entity;

import java.util.ArrayList;
import java.util.List;

public class MessageTplExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    protected int start = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public MessageTplExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setStart(int start) {
        this.start=start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public int getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTplidIsNull() {
            addCriterion("tplid is null");
            return (Criteria) this;
        }

        public Criteria andTplidIsNotNull() {
            addCriterion("tplid is not null");
            return (Criteria) this;
        }

        public Criteria andTplidEqualTo(String value) {
            addCriterion("tplid =", value, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidNotEqualTo(String value) {
            addCriterion("tplid <>", value, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidGreaterThan(String value) {
            addCriterion("tplid >", value, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidGreaterThanOrEqualTo(String value) {
            addCriterion("tplid >=", value, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidLessThan(String value) {
            addCriterion("tplid <", value, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidLessThanOrEqualTo(String value) {
            addCriterion("tplid <=", value, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidLike(String value) {
            addCriterion("tplid like", value, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidNotLike(String value) {
            addCriterion("tplid not like", value, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidIn(List<String> values) {
            addCriterion("tplid in", values, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidNotIn(List<String> values) {
            addCriterion("tplid not in", values, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidBetween(String value1, String value2) {
            addCriterion("tplid between", value1, value2, "tplid");
            return (Criteria) this;
        }

        public Criteria andTplidNotBetween(String value1, String value2) {
            addCriterion("tplid not between", value1, value2, "tplid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSendtypeIsNull() {
            addCriterion("sendtype is null");
            return (Criteria) this;
        }

        public Criteria andSendtypeIsNotNull() {
            addCriterion("sendtype is not null");
            return (Criteria) this;
        }

        public Criteria andSendtypeEqualTo(String value) {
            addCriterion("sendtype =", value, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeNotEqualTo(String value) {
            addCriterion("sendtype <>", value, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeGreaterThan(String value) {
            addCriterion("sendtype >", value, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeGreaterThanOrEqualTo(String value) {
            addCriterion("sendtype >=", value, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeLessThan(String value) {
            addCriterion("sendtype <", value, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeLessThanOrEqualTo(String value) {
            addCriterion("sendtype <=", value, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeLike(String value) {
            addCriterion("sendtype like", value, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeNotLike(String value) {
            addCriterion("sendtype not like", value, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeIn(List<String> values) {
            addCriterion("sendtype in", values, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeNotIn(List<String> values) {
            addCriterion("sendtype not in", values, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeBetween(String value1, String value2) {
            addCriterion("sendtype between", value1, value2, "sendtype");
            return (Criteria) this;
        }

        public Criteria andSendtypeNotBetween(String value1, String value2) {
            addCriterion("sendtype not between", value1, value2, "sendtype");
            return (Criteria) this;
        }

        public Criteria andBitypeIsNull() {
            addCriterion("bitype is null");
            return (Criteria) this;
        }

        public Criteria andBitypeIsNotNull() {
            addCriterion("bitype is not null");
            return (Criteria) this;
        }

        public Criteria andBitypeEqualTo(String value) {
            addCriterion("bitype =", value, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeNotEqualTo(String value) {
            addCriterion("bitype <>", value, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeGreaterThan(String value) {
            addCriterion("bitype >", value, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeGreaterThanOrEqualTo(String value) {
            addCriterion("bitype >=", value, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeLessThan(String value) {
            addCriterion("bitype <", value, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeLessThanOrEqualTo(String value) {
            addCriterion("bitype <=", value, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeLike(String value) {
            addCriterion("bitype like", value, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeNotLike(String value) {
            addCriterion("bitype not like", value, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeIn(List<String> values) {
            addCriterion("bitype in", values, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeNotIn(List<String> values) {
            addCriterion("bitype not in", values, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeBetween(String value1, String value2) {
            addCriterion("bitype between", value1, value2, "bitype");
            return (Criteria) this;
        }

        public Criteria andBitypeNotBetween(String value1, String value2) {
            addCriterion("bitype not between", value1, value2, "bitype");
            return (Criteria) this;
        }

        public Criteria andIshtmlIsNull() {
            addCriterion("ishtml is null");
            return (Criteria) this;
        }

        public Criteria andIshtmlIsNotNull() {
            addCriterion("ishtml is not null");
            return (Criteria) this;
        }

        public Criteria andIshtmlEqualTo(Integer value) {
            addCriterion("ishtml =", value, "ishtml");
            return (Criteria) this;
        }

        public Criteria andIshtmlNotEqualTo(Integer value) {
            addCriterion("ishtml <>", value, "ishtml");
            return (Criteria) this;
        }

        public Criteria andIshtmlGreaterThan(Integer value) {
            addCriterion("ishtml >", value, "ishtml");
            return (Criteria) this;
        }

        public Criteria andIshtmlGreaterThanOrEqualTo(Integer value) {
            addCriterion("ishtml >=", value, "ishtml");
            return (Criteria) this;
        }

        public Criteria andIshtmlLessThan(Integer value) {
            addCriterion("ishtml <", value, "ishtml");
            return (Criteria) this;
        }

        public Criteria andIshtmlLessThanOrEqualTo(Integer value) {
            addCriterion("ishtml <=", value, "ishtml");
            return (Criteria) this;
        }

        public Criteria andIshtmlIn(List<Integer> values) {
            addCriterion("ishtml in", values, "ishtml");
            return (Criteria) this;
        }

        public Criteria andIshtmlNotIn(List<Integer> values) {
            addCriterion("ishtml not in", values, "ishtml");
            return (Criteria) this;
        }

        public Criteria andIshtmlBetween(Integer value1, Integer value2) {
            addCriterion("ishtml between", value1, value2, "ishtml");
            return (Criteria) this;
        }

        public Criteria andIshtmlNotBetween(Integer value1, Integer value2) {
            addCriterion("ishtml not between", value1, value2, "ishtml");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("subject is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("subject =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("subject <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("subject >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("subject >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("subject <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("subject <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("subject like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("subject not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("subject in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("subject not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("subject between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("subject not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andIsuploadIsNull() {
            addCriterion("isupload is null");
            return (Criteria) this;
        }

        public Criteria andIsuploadIsNotNull() {
            addCriterion("isupload is not null");
            return (Criteria) this;
        }

        public Criteria andIsuploadEqualTo(String value) {
            addCriterion("isupload =", value, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadNotEqualTo(String value) {
            addCriterion("isupload <>", value, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadGreaterThan(String value) {
            addCriterion("isupload >", value, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadGreaterThanOrEqualTo(String value) {
            addCriterion("isupload >=", value, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadLessThan(String value) {
            addCriterion("isupload <", value, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadLessThanOrEqualTo(String value) {
            addCriterion("isupload <=", value, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadLike(String value) {
            addCriterion("isupload like", value, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadNotLike(String value) {
            addCriterion("isupload not like", value, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadIn(List<String> values) {
            addCriterion("isupload in", values, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadNotIn(List<String> values) {
            addCriterion("isupload not in", values, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadBetween(String value1, String value2) {
            addCriterion("isupload between", value1, value2, "isupload");
            return (Criteria) this;
        }

        public Criteria andIsuploadNotBetween(String value1, String value2) {
            addCriterion("isupload not between", value1, value2, "isupload");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mg_message_tpl
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 20 17:28:14 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}