package com.lpcode.modules.blsp.entity;

public class PrjCodeGenerator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prj_code_generator.id
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prj_code_generator.year
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prj_code_generator.month
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Integer month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prj_code_generator.seq
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prj_code_generator.seq_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    private String seqType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prj_code_generator.id
     *
     * @return the value of prj_code_generator.id
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prj_code_generator.id
     *
     * @param id the value for prj_code_generator.id
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prj_code_generator.year
     *
     * @return the value of prj_code_generator.year
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prj_code_generator.year
     *
     * @param year the value for prj_code_generator.year
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prj_code_generator.month
     *
     * @return the value of prj_code_generator.month
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prj_code_generator.month
     *
     * @param month the value for prj_code_generator.month
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prj_code_generator.seq
     *
     * @return the value of prj_code_generator.seq
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prj_code_generator.seq
     *
     * @param seq the value for prj_code_generator.seq
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prj_code_generator.seq_type
     *
     * @return the value of prj_code_generator.seq_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public String getSeqType() {
        return seqType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prj_code_generator.seq_type
     *
     * @param seqType the value for prj_code_generator.seq_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    public void setSeqType(String seqType) {
        this.seqType = seqType;
    }
}