{<#rt>
"zjlx":"${servicePushDto.zjlx!""}",<#rt>
"zjhm":"${servicePushDto.zjhm!""}",<#rt>
"xmlx":"${servicePushDto.xmlx!""}",<#rt>
"prjCode":"${servicePushDto.prjCode!""}",<#rt>
"prjCat":"${servicePushDto.prjCat!""}",<#rt>
"agentName":"${servicePushDto.agentName!""}",<#rt>
"agentMphone":"${servicePushDto.agentMphone!""}",<#rt>
"agentPhone":"${servicePushDto.agentPhone!""}",<#rt>
"prjName":"${servicePushDto.prjName!""}",<#rt>
"prjNature":"${servicePushDto.prjNature!""}",<#rt>
"prjAddr":"${servicePushDto.prjAddr!""}",<#rt>
"prjFloorSpace":"${servicePushDto.prjFloorSpace!""}",<#rt>
"prjRedlineSpace":"${servicePushDto.prjRedlineSpace!""}",<#rt>
"prjDescription":"${servicePushDto.prjDescription!""}",<#rt>
"priceType":"${servicePushDto.priceType!""}",<#rt>
"landType":"${servicePushDto.landType!""}",<#rt>
"useageType":"${servicePushDto.useageType!""}",<#rt>
"lpcodeAddr":"${servicePushDto.lpcodeAddr!""}",<#rt>
"isNeedPreAudit":"${servicePushDto.isNeedPreAudit!""}",<#rt>
"isSpecialProject":"${servicePushDto.isSpecialProject!""}",<#rt>
"isWithBasePart":"${servicePushDto.isWithBasePart!""}",<#rt>
"isItType":"${servicePushDto.isItType!""}",<#rt>
"isGovType":"${servicePushDto.isGovType!""}",<#rt>
"investEstimate":"${servicePushDto.investEstimate!""}",<#rt>
"fundSource":"${servicePushDto.fundSource!""}"<#rt>
}<#rt>