{<#rt>
'sblsh':'${serviceReport.sblsh!""}',<#rt>
'sxbm':'${serviceReport.sxbm!""}',<#rt>
'sphjdm':'${serviceReport.sphjdm!""}',<#rt>
'sphjmc':'${serviceReport.sphjmc!""}',<#rt>
'spbmmc':'${serviceReport.spbmmc!""}',<#rt>
'spbmzzjdmd':'${serviceReport.spbmzzjdmd!""}',<#rt>
'xzqhdm':'${serviceReport.xzqhdm!""}',<#rt>
'sprxm':'${serviceReport.sprxm!""}',<#rt>
'sprzwdm':'${serviceReport.sprzwdm!""}',<#rt>
'sprzwmc':'${serviceReport.sprzwmc!""}',<#rt>
'spyj':'${serviceReport.spyj!""}',<#rt>
'spsj':'${serviceReport.spsj!""}',<#rt>
'sphjztdm':'1',<#rt>
'transactor':'${serviceReport.transactorname!""}',<#rt>
'bz':'',<#rt>
'byzd':''<#rt>
}<#rt>