{<#rt>
'sblsh':'${serviceReport.sblsh!""}',<#rt>
'sxbm':'${serviceReport.sxbm!""}',<#rt>
'xh':'${serviceReport.xh!""}',<#rt>
'tbcxzl':'${serviceReport.tbcxzl!""}',<#rt>
'tbcxzlmc':'${serviceReport.tbcxzlmc!""}',<#rt>
'tbcxksrq':'${serviceReport.tbcxksrq!""}',<#rt>
'tbcxpzr':'${serviceReport.tbcxpzr!""}',<#rt>
'tbcxqdly':'${serviceReport.tbcxqdly!""}',<#rt>
'sqnr':'${serviceReport.sqnr!""}',<#rt>
'tbcxsx':'${serviceReport.tbcxsx!""}',<#rt>
'tbcxsxdw':'${serviceReport.tbcxsxdw!""}',<#rt>
'xzqhdm':'440404',<#rt>
'transactor':'${serviceReport.transactor!"审批人员"}',<#rt>
'tbcxsort':'${serviceReport.tbcxsort!""}',<#rt>
'bz':'',<#rt>
'byzd':''<#rt>
}<#rt>