{<#rt>
"companyCode":"${serviceReuseDto.zjhm!""}",<#rt>
"prjType":"${serviceReuseDto.xmlx!""}",<#rt>
"prjCode":"${serviceReuseDto.prjCode!""}",<#rt>
"prjCat":"${serviceReuseDto.prjCat!""}",<#rt>
"agentName":"${serviceReuseDto.agentName!""}",<#rt>
"agentMphone":"${serviceReuseDto.agentMphone!""}",<#rt>
"agentPhone":"${serviceReuseDto.agentPhone!""}",<#rt>
"prjName":"${serviceReuseDto.prjName!""}",<#rt>
"prjNature":"${serviceReuseDto.prjNature!""}",<#rt>
"prjAddr":"${serviceReuseDto.prjAddr!""}",<#rt>
"prjFloorSpace":"${serviceReuseDto.prjFloorSpace!""}",<#rt>
"prjRedlineSpace":"${serviceReuseDto.prjRedlineSpace!""}",<#rt>
"prjDescription":"${serviceReuseDto.prjDescription!""}",<#rt>
"priceType":"${serviceReuseDto.priceType!""}",<#rt>
"landType":"${serviceReuseDto.landType!""}",<#rt>
"investEstimate":"${serviceReuseDto.investEstimate!""}",<#rt>
"fundSource":"${serviceReuseDto.fundSource!""}",<#rt>
"company":"${serviceReuseDto.qymc!""}",<#rt>
"companyAddr":"${serviceReuseDto.dz!""}",<#rt>
"entityPhone":"${serviceReuseDto.gddh!""}",<#rt>
"entityMphone":"${serviceReuseDto.sj!""}",<#rt>
"legalEntity":"${serviceReuseDto.frxm!""}"<#rt>
}<#rt>