package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.DimPauseType;
import com.lpcode.modules.blsp.entity.DimPauseTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DimPauseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int countByExample(DimPauseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByExample(DimPauseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insert(DimPauseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insertSelective(DimPauseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<DimPauseType> selectByExample(DimPauseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    DimPauseType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") DimPauseType record, @Param("example") DimPauseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExample(@Param("record") DimPauseType record, @Param("example") DimPauseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeySelective(DimPauseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKey(DimPauseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<DimPauseType> selectByEntitySelective(DimPauseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    DimPauseType selectOneByEntitySelective(DimPauseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<DimPauseType> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<DimPauseType> pagedSelectByExample(@Param("example") DimPauseTypeExample example, @Param("page") Page<DimPauseType> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<DimPauseType> pagedSelectByEntity(@Param("record") DimPauseType record, @Param("page") Page<DimPauseType> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dim_pause_type
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<DimPauseType> SelectByPrimaryKeyList(List<Long> idList);
}