package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormZjJsgcZljdzcbJs;
import com.lpcode.modules.blsp.entity.FormZjJsgcZljdzcbJsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormZjJsgcZljdzcbJsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int countByExample(FormZjJsgcZljdzcbJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int deleteByExample(FormZjJsgcZljdzcbJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int deleteByPrimaryKey(Long bId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int insert(FormZjJsgcZljdzcbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int insertSelective(FormZjJsgcZljdzcbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    List<FormZjJsgcZljdzcbJs> selectByExample(FormZjJsgcZljdzcbJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    FormZjJsgcZljdzcbJs selectByPrimaryKey(Long bId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormZjJsgcZljdzcbJs record, @Param("example") FormZjJsgcZljdzcbJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByExample(@Param("record") FormZjJsgcZljdzcbJs record, @Param("example") FormZjJsgcZljdzcbJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByPrimaryKeySelective(FormZjJsgcZljdzcbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByPrimaryKey(FormZjJsgcZljdzcbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    List<FormZjJsgcZljdzcbJs> selectByEntitySelective(FormZjJsgcZljdzcbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    FormZjJsgcZljdzcbJs selectOneByEntitySelective(FormZjJsgcZljdzcbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormZjJsgcZljdzcbJs> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    Page<FormZjJsgcZljdzcbJs> pagedSelectByExample(@Param("example") FormZjJsgcZljdzcbJsExample example, @Param("page") Page<FormZjJsgcZljdzcbJs> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    Page<FormZjJsgcZljdzcbJs> pagedSelectByEntity(@Param("record") FormZjJsgcZljdzcbJs record, @Param("page") Page<FormZjJsgcZljdzcbJs> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_js
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    List<FormZjJsgcZljdzcbJs> SelectByPrimaryKeyList(List<Long> bIdList);
}