package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormRfYdjsJgsb;
import com.lpcode.modules.blsp.entity.FormRfYdjsJgsbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormRfYdjsJgsbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    int countByExample(FormRfYdjsJgsbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    int deleteByExample(FormRfYdjsJgsbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    int insert(FormRfYdjsJgsb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    int insertSelective(FormRfYdjsJgsb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    List<FormRfYdjsJgsb> selectByExample(FormRfYdjsJgsbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    FormRfYdjsJgsb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormRfYdjsJgsb record, @Param("example") FormRfYdjsJgsbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    int updateByExample(@Param("record") FormRfYdjsJgsb record, @Param("example") FormRfYdjsJgsbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    int updateByPrimaryKeySelective(FormRfYdjsJgsb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    int updateByPrimaryKey(FormRfYdjsJgsb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    List<FormRfYdjsJgsb> selectByEntitySelective(FormRfYdjsJgsb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    FormRfYdjsJgsb selectOneByEntitySelective(FormRfYdjsJgsb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormRfYdjsJgsb> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    Page<FormRfYdjsJgsb> pagedSelectByExample(@Param("example") FormRfYdjsJgsbExample example, @Param("page") Page<FormRfYdjsJgsb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    Page<FormRfYdjsJgsb> pagedSelectByEntity(@Param("record") FormRfYdjsJgsb record, @Param("page") Page<FormRfYdjsJgsb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_ydjs_jgsb
     *
     * @mbggenerated Thu Jun 30 10:34:02 CST 2016
     */
    List<FormRfYdjsJgsb> SelectByPrimaryKeyList(List<Long> idList);
}