package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormQxSjshSqsDz;
import com.lpcode.modules.blsp.entity.FormQxSjshSqsDzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormQxSjshSqsDzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    int countByExample(FormQxSjshSqsDzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    int deleteByExample(FormQxSjshSqsDzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    int deleteByPrimaryKey(Long eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    int insert(FormQxSjshSqsDz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    int insertSelective(FormQxSjshSqsDz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    List<FormQxSjshSqsDz> selectByExample(FormQxSjshSqsDzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    FormQxSjshSqsDz selectByPrimaryKey(Long eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormQxSjshSqsDz record, @Param("example") FormQxSjshSqsDzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    int updateByExample(@Param("record") FormQxSjshSqsDz record, @Param("example") FormQxSjshSqsDzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    int updateByPrimaryKeySelective(FormQxSjshSqsDz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    int updateByPrimaryKey(FormQxSjshSqsDz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    List<FormQxSjshSqsDz> selectByEntitySelective(FormQxSjshSqsDz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    FormQxSjshSqsDz selectOneByEntitySelective(FormQxSjshSqsDz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormQxSjshSqsDz> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    Page<FormQxSjshSqsDz> pagedSelectByExample(@Param("example") FormQxSjshSqsDzExample example,@Param("page") Page<FormQxSjshSqsDz> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    Page<FormQxSjshSqsDz> pagedSelectByEntity(@Param("record") FormQxSjshSqsDz record,@Param("page") Page<FormQxSjshSqsDz> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sqs_dz
     *
     * @mbggenerated Mon Jun 20 18:32:05 CST 2016
     */
    List<FormQxSjshSqsDz> SelectByPrimaryKeyList(List<Long> eIdList);
}