package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormZjJsgcXmjnk;
import com.lpcode.modules.blsp.entity.FormZjJsgcXmjnkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormZjJsgcXmjnkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    int countByExample(FormZjJsgcXmjnkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    int deleteByExample(FormZjJsgcXmjnkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    int insert(FormZjJsgcXmjnk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    int insertSelective(FormZjJsgcXmjnk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    List<FormZjJsgcXmjnk> selectByExample(FormZjJsgcXmjnkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    FormZjJsgcXmjnk selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormZjJsgcXmjnk record, @Param("example") FormZjJsgcXmjnkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    int updateByExample(@Param("record") FormZjJsgcXmjnk record, @Param("example") FormZjJsgcXmjnkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    int updateByPrimaryKeySelective(FormZjJsgcXmjnk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    int updateByPrimaryKey(FormZjJsgcXmjnk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    List<FormZjJsgcXmjnk> selectByEntitySelective(FormZjJsgcXmjnk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    FormZjJsgcXmjnk selectOneByEntitySelective(FormZjJsgcXmjnk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormZjJsgcXmjnk> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    Page<FormZjJsgcXmjnk> pagedSelectByExample(@Param("example") FormZjJsgcXmjnkExample example, @Param("page") Page<FormZjJsgcXmjnk> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    Page<FormZjJsgcXmjnk> pagedSelectByEntity(@Param("record") FormZjJsgcXmjnk record, @Param("page") Page<FormZjJsgcXmjnk> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_xmjnk
     *
     * @mbggenerated Mon Jun 27 11:12:49 CST 2016
     */
    List<FormZjJsgcXmjnk> SelectByPrimaryKeyList(List<Long> idList);
}