package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormZjSgqyNmggz;
import com.lpcode.modules.blsp.entity.FormZjSgqyNmggzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormZjSgqyNmggzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    int countByExample(FormZjSgqyNmggzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    int deleteByExample(FormZjSgqyNmggzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    int insert(FormZjSgqyNmggz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    int insertSelective(FormZjSgqyNmggz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    List<FormZjSgqyNmggz> selectByExample(FormZjSgqyNmggzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    FormZjSgqyNmggz selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormZjSgqyNmggz record, @Param("example") FormZjSgqyNmggzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    int updateByExample(@Param("record") FormZjSgqyNmggz record, @Param("example") FormZjSgqyNmggzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    int updateByPrimaryKeySelective(FormZjSgqyNmggz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    int updateByPrimaryKey(FormZjSgqyNmggz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    List<FormZjSgqyNmggz> selectByEntitySelective(FormZjSgqyNmggz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    FormZjSgqyNmggz selectOneByEntitySelective(FormZjSgqyNmggz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormZjSgqyNmggz> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    Page<FormZjSgqyNmggz> pagedSelectByExample(@Param("example") FormZjSgqyNmggzExample example, @Param("page") Page<FormZjSgqyNmggz> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    Page<FormZjSgqyNmggz> pagedSelectByEntity(@Param("record") FormZjSgqyNmggz record, @Param("page") Page<FormZjSgqyNmggz> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgqy_nmggz
     *
     * @mbggenerated Mon Jun 27 10:48:37 CST 2016
     */
    List<FormZjSgqyNmggz> SelectByPrimaryKeyList(List<Long> idList);
}