package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormHbJsxmGyxmCp;
import com.lpcode.modules.blsp.entity.FormHbJsxmGyxmCpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormHbJsxmGyxmCpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int countByExample(FormHbJsxmGyxmCpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int deleteByExample(FormHbJsxmGyxmCpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int deleteByPrimaryKey(Long pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int insert(FormHbJsxmGyxmCp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int insertSelective(FormHbJsxmGyxmCp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    List<FormHbJsxmGyxmCp> selectByExample(FormHbJsxmGyxmCpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    FormHbJsxmGyxmCp selectByPrimaryKey(Long pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormHbJsxmGyxmCp record, @Param("example") FormHbJsxmGyxmCpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int updateByExample(@Param("record") FormHbJsxmGyxmCp record, @Param("example") FormHbJsxmGyxmCpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int updateByPrimaryKeySelective(FormHbJsxmGyxmCp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int updateByPrimaryKey(FormHbJsxmGyxmCp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    List<FormHbJsxmGyxmCp> selectByEntitySelective(FormHbJsxmGyxmCp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    FormHbJsxmGyxmCp selectOneByEntitySelective(FormHbJsxmGyxmCp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormHbJsxmGyxmCp> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    Page<FormHbJsxmGyxmCp> pagedSelectByExample(@Param("example") FormHbJsxmGyxmCpExample example, @Param("page") Page<FormHbJsxmGyxmCp> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    Page<FormHbJsxmGyxmCp> pagedSelectByEntity(@Param("record") FormHbJsxmGyxmCp record, @Param("page") Page<FormHbJsxmGyxmCp> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_cp
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    List<FormHbJsxmGyxmCp> SelectByPrimaryKeyList(List<Long> pIdList);
}