package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormZjJsgcZljdzcb;
import com.lpcode.modules.blsp.entity.FormZjJsgcZljdzcbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormZjJsgcZljdzcbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int countByExample(FormZjJsgcZljdzcbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int deleteByExample(FormZjJsgcZljdzcbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int insert(FormZjJsgcZljdzcb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int insertSelective(FormZjJsgcZljdzcb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    List<FormZjJsgcZljdzcb> selectByExample(FormZjJsgcZljdzcbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    FormZjJsgcZljdzcb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormZjJsgcZljdzcb record, @Param("example") FormZjJsgcZljdzcbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByExample(@Param("record") FormZjJsgcZljdzcb record, @Param("example") FormZjJsgcZljdzcbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByPrimaryKeySelective(FormZjJsgcZljdzcb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByPrimaryKey(FormZjJsgcZljdzcb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    List<FormZjJsgcZljdzcb> selectByEntitySelective(FormZjJsgcZljdzcb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    FormZjJsgcZljdzcb selectOneByEntitySelective(FormZjJsgcZljdzcb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormZjJsgcZljdzcb> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    Page<FormZjJsgcZljdzcb> pagedSelectByExample(@Param("example") FormZjJsgcZljdzcbExample example, @Param("page") Page<FormZjJsgcZljdzcb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    Page<FormZjJsgcZljdzcb> pagedSelectByEntity(@Param("record") FormZjJsgcZljdzcb record, @Param("page") Page<FormZjJsgcZljdzcb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    List<FormZjJsgcZljdzcb> SelectByPrimaryKeyList(List<Long> idList);
}