package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormZjSgxkSqbJl;
import com.lpcode.modules.blsp.entity.FormZjSgxkSqbJlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormZjSgxkSqbJlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int countByExample(FormZjSgxkSqbJlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int deleteByExample(FormZjSgxkSqbJlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int deleteByPrimaryKey(Long sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int insert(FormZjSgxkSqbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int insertSelective(FormZjSgxkSqbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    List<FormZjSgxkSqbJl> selectByExample(FormZjSgxkSqbJlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    FormZjSgxkSqbJl selectByPrimaryKey(Long sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormZjSgxkSqbJl record, @Param("example") FormZjSgxkSqbJlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int updateByExample(@Param("record") FormZjSgxkSqbJl record, @Param("example") FormZjSgxkSqbJlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int updateByPrimaryKeySelective(FormZjSgxkSqbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int updateByPrimaryKey(FormZjSgxkSqbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    List<FormZjSgxkSqbJl> selectByEntitySelective(FormZjSgxkSqbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    FormZjSgxkSqbJl selectOneByEntitySelective(FormZjSgxkSqbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormZjSgxkSqbJl> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    Page<FormZjSgxkSqbJl> pagedSelectByExample(@Param("example") FormZjSgxkSqbJlExample example, @Param("page") Page<FormZjSgxkSqbJl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    Page<FormZjSgxkSqbJl> pagedSelectByEntity(@Param("record") FormZjSgxkSqbJl record, @Param("page") Page<FormZjSgxkSqbJl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_jl
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    List<FormZjSgxkSqbJl> SelectByPrimaryKeyList(List<Long> sIdList);
}