package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormZjJsgcZljdzcbJl;
import com.lpcode.modules.blsp.entity.FormZjJsgcZljdzcbJlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormZjJsgcZljdzcbJlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int countByExample(FormZjJsgcZljdzcbJlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int deleteByExample(FormZjJsgcZljdzcbJlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int deleteByPrimaryKey(Long sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int insert(FormZjJsgcZljdzcbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int insertSelective(FormZjJsgcZljdzcbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    List<FormZjJsgcZljdzcbJl> selectByExample(FormZjJsgcZljdzcbJlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    FormZjJsgcZljdzcbJl selectByPrimaryKey(Long sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormZjJsgcZljdzcbJl record, @Param("example") FormZjJsgcZljdzcbJlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByExample(@Param("record") FormZjJsgcZljdzcbJl record, @Param("example") FormZjJsgcZljdzcbJlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByPrimaryKeySelective(FormZjJsgcZljdzcbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    int updateByPrimaryKey(FormZjJsgcZljdzcbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    List<FormZjJsgcZljdzcbJl> selectByEntitySelective(FormZjJsgcZljdzcbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    FormZjJsgcZljdzcbJl selectOneByEntitySelective(FormZjJsgcZljdzcbJl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormZjJsgcZljdzcbJl> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    Page<FormZjJsgcZljdzcbJl> pagedSelectByExample(@Param("example") FormZjJsgcZljdzcbJlExample example, @Param("page") Page<FormZjJsgcZljdzcbJl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    Page<FormZjJsgcZljdzcbJl> pagedSelectByEntity(@Param("record") FormZjJsgcZljdzcbJl record, @Param("page") Page<FormZjJsgcZljdzcbJl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_jsgc_zljdzcb_jl
     *
     * @mbggenerated Mon Jun 27 11:00:32 CST 2016
     */
    List<FormZjJsgcZljdzcbJl> SelectByPrimaryKeyList(List<Long> sIdList);
}