package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormGhJsgcSzGhysCl;
import com.lpcode.modules.blsp.entity.FormGhJsgcSzGhysClExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormGhJsgcSzGhysClMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int countByExample(FormGhJsgcSzGhysClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int deleteByExample(FormGhJsgcSzGhysClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int deleteByPrimaryKey(Long mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int insert(FormGhJsgcSzGhysCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int insertSelective(FormGhJsgcSzGhysCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    List<FormGhJsgcSzGhysCl> selectByExample(FormGhJsgcSzGhysClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    FormGhJsgcSzGhysCl selectByPrimaryKey(Long mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormGhJsgcSzGhysCl record, @Param("example") FormGhJsgcSzGhysClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByExample(@Param("record") FormGhJsgcSzGhysCl record, @Param("example") FormGhJsgcSzGhysClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByPrimaryKeySelective(FormGhJsgcSzGhysCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByPrimaryKey(FormGhJsgcSzGhysCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    List<FormGhJsgcSzGhysCl> selectByEntitySelective(FormGhJsgcSzGhysCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    FormGhJsgcSzGhysCl selectOneByEntitySelective(FormGhJsgcSzGhysCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormGhJsgcSzGhysCl> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    Page<FormGhJsgcSzGhysCl> pagedSelectByExample(@Param("example") FormGhJsgcSzGhysClExample example, @Param("page") Page<FormGhJsgcSzGhysCl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    Page<FormGhJsgcSzGhysCl> pagedSelectByEntity(@Param("record") FormGhJsgcSzGhysCl record, @Param("page") Page<FormGhJsgcSzGhysCl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghys_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    List<FormGhJsgcSzGhysCl> SelectByPrimaryKeyList(List<Long> mIdList);
}