package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormGhJsgcSzGhxkGx;
import com.lpcode.modules.blsp.entity.FormGhJsgcSzGhxkGxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormGhJsgcSzGhxkGxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int countByExample(FormGhJsgcSzGhxkGxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int deleteByExample(FormGhJsgcSzGhxkGxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int deleteByPrimaryKey(Long pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int insert(FormGhJsgcSzGhxkGx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int insertSelective(FormGhJsgcSzGhxkGx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    List<FormGhJsgcSzGhxkGx> selectByExample(FormGhJsgcSzGhxkGxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    FormGhJsgcSzGhxkGx selectByPrimaryKey(Long pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormGhJsgcSzGhxkGx record, @Param("example") FormGhJsgcSzGhxkGxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByExample(@Param("record") FormGhJsgcSzGhxkGx record, @Param("example") FormGhJsgcSzGhxkGxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByPrimaryKeySelective(FormGhJsgcSzGhxkGx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByPrimaryKey(FormGhJsgcSzGhxkGx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    List<FormGhJsgcSzGhxkGx> selectByEntitySelective(FormGhJsgcSzGhxkGx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    FormGhJsgcSzGhxkGx selectOneByEntitySelective(FormGhJsgcSzGhxkGx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormGhJsgcSzGhxkGx> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    Page<FormGhJsgcSzGhxkGx> pagedSelectByExample(@Param("example") FormGhJsgcSzGhxkGxExample example, @Param("page") Page<FormGhJsgcSzGhxkGx> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    Page<FormGhJsgcSzGhxkGx> pagedSelectByEntity(@Param("record") FormGhJsgcSzGhxkGx record, @Param("page") Page<FormGhJsgcSzGhxkGx> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_sz_ghxk_gx
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    List<FormGhJsgcSzGhxkGx> SelectByPrimaryKeyList(List<Long> pIdList);
}