package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormGtJsydSqbZl;
import com.lpcode.modules.blsp.entity.FormGtJsydSqbZlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormGtJsydSqbZlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    int countByExample(FormGtJsydSqbZlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    int deleteByExample(FormGtJsydSqbZlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    int deleteByPrimaryKey(Long dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    int insert(FormGtJsydSqbZl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    int insertSelective(FormGtJsydSqbZl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    List<FormGtJsydSqbZl> selectByExample(FormGtJsydSqbZlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    FormGtJsydSqbZl selectByPrimaryKey(Long dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormGtJsydSqbZl record, @Param("example") FormGtJsydSqbZlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    int updateByExample(@Param("record") FormGtJsydSqbZl record, @Param("example") FormGtJsydSqbZlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    int updateByPrimaryKeySelective(FormGtJsydSqbZl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    int updateByPrimaryKey(FormGtJsydSqbZl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    List<FormGtJsydSqbZl> selectByEntitySelective(FormGtJsydSqbZl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    FormGtJsydSqbZl selectOneByEntitySelective(FormGtJsydSqbZl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormGtJsydSqbZl> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    Page<FormGtJsydSqbZl> pagedSelectByExample(@Param("example") FormGtJsydSqbZlExample example,@Param("page") Page<FormGtJsydSqbZl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    Page<FormGtJsydSqbZl> pagedSelectByEntity(@Param("record") FormGtJsydSqbZl record,@Param("page") Page<FormGtJsydSqbZl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb_zl
     *
     * @mbggenerated Mon Jun 20 14:57:20 CST 2016
     */
    List<FormGtJsydSqbZl> SelectByPrimaryKeyList(List<Long> dIdList);
}