package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormHbJsxmGyxmSb;
import com.lpcode.modules.blsp.entity.FormHbJsxmGyxmSbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormHbJsxmGyxmSbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int countByExample(FormHbJsxmGyxmSbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int deleteByExample(FormHbJsxmGyxmSbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int deleteByPrimaryKey(Long eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int insert(FormHbJsxmGyxmSb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int insertSelective(FormHbJsxmGyxmSb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    List<FormHbJsxmGyxmSb> selectByExample(FormHbJsxmGyxmSbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    FormHbJsxmGyxmSb selectByPrimaryKey(Long eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormHbJsxmGyxmSb record, @Param("example") FormHbJsxmGyxmSbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int updateByExample(@Param("record") FormHbJsxmGyxmSb record, @Param("example") FormHbJsxmGyxmSbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int updateByPrimaryKeySelective(FormHbJsxmGyxmSb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    int updateByPrimaryKey(FormHbJsxmGyxmSb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    List<FormHbJsxmGyxmSb> selectByEntitySelective(FormHbJsxmGyxmSb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    FormHbJsxmGyxmSb selectOneByEntitySelective(FormHbJsxmGyxmSb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormHbJsxmGyxmSb> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    Page<FormHbJsxmGyxmSb> pagedSelectByExample(@Param("example") FormHbJsxmGyxmSbExample example, @Param("page") Page<FormHbJsxmGyxmSb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    Page<FormHbJsxmGyxmSb> pagedSelectByEntity(@Param("record") FormHbJsxmGyxmSb record, @Param("page") Page<FormHbJsxmGyxmSb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_gyxm_sb
     *
     * @mbggenerated Tue Jul 12 16:20:39 CST 2016
     */
    List<FormHbJsxmGyxmSb> SelectByPrimaryKeyList(List<Long> eIdList);
}