package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormZjSgxkSqbJs;
import com.lpcode.modules.blsp.entity.FormZjSgxkSqbJsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormZjSgxkSqbJsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int countByExample(FormZjSgxkSqbJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int deleteByExample(FormZjSgxkSqbJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int deleteByPrimaryKey(Long bId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int insert(FormZjSgxkSqbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int insertSelective(FormZjSgxkSqbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    List<FormZjSgxkSqbJs> selectByExample(FormZjSgxkSqbJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    FormZjSgxkSqbJs selectByPrimaryKey(Long bId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormZjSgxkSqbJs record, @Param("example") FormZjSgxkSqbJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int updateByExample(@Param("record") FormZjSgxkSqbJs record, @Param("example") FormZjSgxkSqbJsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int updateByPrimaryKeySelective(FormZjSgxkSqbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    int updateByPrimaryKey(FormZjSgxkSqbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    List<FormZjSgxkSqbJs> selectByEntitySelective(FormZjSgxkSqbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    FormZjSgxkSqbJs selectOneByEntitySelective(FormZjSgxkSqbJs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormZjSgxkSqbJs> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    Page<FormZjSgxkSqbJs> pagedSelectByExample(@Param("example") FormZjSgxkSqbJsExample example, @Param("page") Page<FormZjSgxkSqbJs> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    Page<FormZjSgxkSqbJs> pagedSelectByEntity(@Param("record") FormZjSgxkSqbJs record, @Param("page") Page<FormZjSgxkSqbJs> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_zj_sgxk_sqb_js
     *
     * @mbggenerated Fri Jun 24 13:12:10 CST 2016
     */
    List<FormZjSgxkSqbJs> SelectByPrimaryKeyList(List<Long> bIdList);
}