package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormHbJsxmDscy;
import com.lpcode.modules.blsp.entity.FormHbJsxmDscyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormHbJsxmDscyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    int countByExample(FormHbJsxmDscyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    int deleteByExample(FormHbJsxmDscyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    int insert(FormHbJsxmDscy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    int insertSelective(FormHbJsxmDscy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    List<FormHbJsxmDscy> selectByExample(FormHbJsxmDscyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    FormHbJsxmDscy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormHbJsxmDscy record, @Param("example") FormHbJsxmDscyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    int updateByExample(@Param("record") FormHbJsxmDscy record, @Param("example") FormHbJsxmDscyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    int updateByPrimaryKeySelective(FormHbJsxmDscy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    int updateByPrimaryKey(FormHbJsxmDscy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    List<FormHbJsxmDscy> selectByEntitySelective(FormHbJsxmDscy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    FormHbJsxmDscy selectOneByEntitySelective(FormHbJsxmDscy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormHbJsxmDscy> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    Page<FormHbJsxmDscy> pagedSelectByExample(@Param("example") FormHbJsxmDscyExample example, @Param("page") Page<FormHbJsxmDscy> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    Page<FormHbJsxmDscy> pagedSelectByEntity(@Param("record") FormHbJsxmDscy record, @Param("page") Page<FormHbJsxmDscy> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_hb_jsxm_dscy
     *
     * @mbggenerated Tue Jul 12 10:42:42 CST 2016
     */
    List<FormHbJsxmDscy> SelectByPrimaryKeyList(List<Long> idList);
}