package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormGhJsgcGhyssqbCl;
import com.lpcode.modules.blsp.entity.FormGhJsgcGhyssqbClExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormGhJsgcGhyssqbClMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int countByExample(FormGhJsgcGhyssqbClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int deleteByExample(FormGhJsgcGhyssqbClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int deleteByPrimaryKey(Long mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int insert(FormGhJsgcGhyssqbCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int insertSelective(FormGhJsgcGhyssqbCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    List<FormGhJsgcGhyssqbCl> selectByExample(FormGhJsgcGhyssqbClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    FormGhJsgcGhyssqbCl selectByPrimaryKey(Long mId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormGhJsgcGhyssqbCl record, @Param("example") FormGhJsgcGhyssqbClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByExample(@Param("record") FormGhJsgcGhyssqbCl record, @Param("example") FormGhJsgcGhyssqbClExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByPrimaryKeySelective(FormGhJsgcGhyssqbCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    int updateByPrimaryKey(FormGhJsgcGhyssqbCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    List<FormGhJsgcGhyssqbCl> selectByEntitySelective(FormGhJsgcGhyssqbCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    FormGhJsgcGhyssqbCl selectOneByEntitySelective(FormGhJsgcGhyssqbCl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormGhJsgcGhyssqbCl> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    Page<FormGhJsgcGhyssqbCl> pagedSelectByExample(@Param("example") FormGhJsgcGhyssqbClExample example, @Param("page") Page<FormGhJsgcGhyssqbCl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    Page<FormGhJsgcGhyssqbCl> pagedSelectByEntity(@Param("record") FormGhJsgcGhyssqbCl record, @Param("page") Page<FormGhJsgcGhyssqbCl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghyssqb_cl
     *
     * @mbggenerated Mon Jun 20 14:23:31 CST 2016
     */
    List<FormGhJsgcGhyssqbCl> SelectByPrimaryKeyList(List<Long> mIdList);
}