package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormGhJsgcGhxksqb;
import com.lpcode.modules.blsp.entity.FormGhJsgcGhxksqbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormGhJsgcGhxksqbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    int countByExample(FormGhJsgcGhxksqbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    int deleteByExample(FormGhJsgcGhxksqbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    int insert(FormGhJsgcGhxksqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    int insertSelective(FormGhJsgcGhxksqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    List<FormGhJsgcGhxksqb> selectByExample(FormGhJsgcGhxksqbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    FormGhJsgcGhxksqb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormGhJsgcGhxksqb record, @Param("example") FormGhJsgcGhxksqbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    int updateByExample(@Param("record") FormGhJsgcGhxksqb record, @Param("example") FormGhJsgcGhxksqbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    int updateByPrimaryKeySelective(FormGhJsgcGhxksqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    int updateByPrimaryKey(FormGhJsgcGhxksqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    List<FormGhJsgcGhxksqb> selectByEntitySelective(FormGhJsgcGhxksqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    FormGhJsgcGhxksqb selectOneByEntitySelective(FormGhJsgcGhxksqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormGhJsgcGhxksqb> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    Page<FormGhJsgcGhxksqb> pagedSelectByExample(@Param("example") FormGhJsgcGhxksqbExample example, @Param("page") Page<FormGhJsgcGhxksqb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    Page<FormGhJsgcGhxksqb> pagedSelectByEntity(@Param("record") FormGhJsgcGhxksqb record, @Param("page") Page<FormGhJsgcGhxksqb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsgc_ghxksqb
     *
     * @mbggenerated Mon Jun 27 14:51:15 CST 2016
     */
    List<FormGhJsgcGhxksqb> SelectByPrimaryKeyList(List<Long> idList);
}