package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormXfJsgcSjshsbbJz;
import com.lpcode.modules.blsp.entity.FormXfJsgcSjshsbbJzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormXfJsgcSjshsbbJzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    int countByExample(FormXfJsgcSjshsbbJzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    int deleteByExample(FormXfJsgcSjshsbbJzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    int deleteByPrimaryKey(Long buildId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    int insert(FormXfJsgcSjshsbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    int insertSelective(FormXfJsgcSjshsbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    List<FormXfJsgcSjshsbbJz> selectByExample(FormXfJsgcSjshsbbJzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    FormXfJsgcSjshsbbJz selectByPrimaryKey(Long buildId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormXfJsgcSjshsbbJz record, @Param("example") FormXfJsgcSjshsbbJzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    int updateByExample(@Param("record") FormXfJsgcSjshsbbJz record, @Param("example") FormXfJsgcSjshsbbJzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    int updateByPrimaryKeySelective(FormXfJsgcSjshsbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    int updateByPrimaryKey(FormXfJsgcSjshsbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    List<FormXfJsgcSjshsbbJz> selectByEntitySelective(FormXfJsgcSjshsbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    FormXfJsgcSjshsbbJz selectOneByEntitySelective(FormXfJsgcSjshsbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormXfJsgcSjshsbbJz> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    Page<FormXfJsgcSjshsbbJz> pagedSelectByExample(@Param("example") FormXfJsgcSjshsbbJzExample example, @Param("page") Page<FormXfJsgcSjshsbbJz> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    Page<FormXfJsgcSjshsbbJz> pagedSelectByEntity(@Param("record") FormXfJsgcSjshsbbJz record, @Param("page") Page<FormXfJsgcSjshsbbJz> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_xf_jsgc_sjshsbb_jz
     *
     * @mbggenerated Mon Jun 27 11:38:40 CST 2016
     */
    List<FormXfJsgcSjshsbbJz> SelectByPrimaryKeyList(List<Long> buildIdList);
}