package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormGtJsydSqb;
import com.lpcode.modules.blsp.entity.FormGtJsydSqbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormGtJsydSqbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    int countByExample(FormGtJsydSqbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    int deleteByExample(FormGtJsydSqbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    int insert(FormGtJsydSqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    int insertSelective(FormGtJsydSqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    List<FormGtJsydSqb> selectByExample(FormGtJsydSqbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    FormGtJsydSqb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormGtJsydSqb record, @Param("example") FormGtJsydSqbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    int updateByExample(@Param("record") FormGtJsydSqb record, @Param("example") FormGtJsydSqbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    int updateByPrimaryKeySelective(FormGtJsydSqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    int updateByPrimaryKey(FormGtJsydSqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    List<FormGtJsydSqb> selectByEntitySelective(FormGtJsydSqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    FormGtJsydSqb selectOneByEntitySelective(FormGtJsydSqb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormGtJsydSqb> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    Page<FormGtJsydSqb> pagedSelectByExample(@Param("example") FormGtJsydSqbExample example, @Param("page") Page<FormGtJsydSqb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    Page<FormGtJsydSqb> pagedSelectByEntity(@Param("record") FormGtJsydSqb record, @Param("page") Page<FormGtJsydSqb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gt_jsyd_sqb
     *
     * @mbggenerated Mon Jun 27 14:06:41 CST 2016
     */
    List<FormGtJsydSqb> SelectByPrimaryKeyList(List<Long> idList);
}