package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormGhJsydGhxk;
import com.lpcode.modules.blsp.entity.FormGhJsydGhxkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormGhJsydGhxkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    int countByExample(FormGhJsydGhxkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    int deleteByExample(FormGhJsydGhxkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    int insert(FormGhJsydGhxk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    int insertSelective(FormGhJsydGhxk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    List<FormGhJsydGhxk> selectByExample(FormGhJsydGhxkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    FormGhJsydGhxk selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormGhJsydGhxk record, @Param("example") FormGhJsydGhxkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    int updateByExample(@Param("record") FormGhJsydGhxk record, @Param("example") FormGhJsydGhxkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    int updateByPrimaryKeySelective(FormGhJsydGhxk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    int updateByPrimaryKey(FormGhJsydGhxk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    List<FormGhJsydGhxk> selectByEntitySelective(FormGhJsydGhxk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    FormGhJsydGhxk selectOneByEntitySelective(FormGhJsydGhxk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormGhJsydGhxk> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    Page<FormGhJsydGhxk> pagedSelectByExample(@Param("example") FormGhJsydGhxkExample example, @Param("page") Page<FormGhJsydGhxk> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    Page<FormGhJsydGhxk> pagedSelectByEntity(@Param("record") FormGhJsydGhxk record, @Param("page") Page<FormGhJsydGhxk> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_gh_jsyd_ghxk
     *
     * @mbggenerated Mon Jun 27 14:16:59 CST 2016
     */
    List<FormGhJsydGhxk> SelectByPrimaryKeyList(List<Long> idList);
}