package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormQxSjshSbbJz;
import com.lpcode.modules.blsp.entity.FormQxSjshSbbJzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormQxSjshSbbJzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    int countByExample(FormQxSjshSbbJzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    int deleteByExample(FormQxSjshSbbJzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    int deleteByPrimaryKey(Long bId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    int insert(FormQxSjshSbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    int insertSelective(FormQxSjshSbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    List<FormQxSjshSbbJz> selectByExample(FormQxSjshSbbJzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    FormQxSjshSbbJz selectByPrimaryKey(Long bId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormQxSjshSbbJz record, @Param("example") FormQxSjshSbbJzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    int updateByExample(@Param("record") FormQxSjshSbbJz record, @Param("example") FormQxSjshSbbJzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    int updateByPrimaryKeySelective(FormQxSjshSbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    int updateByPrimaryKey(FormQxSjshSbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    List<FormQxSjshSbbJz> selectByEntitySelective(FormQxSjshSbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    FormQxSjshSbbJz selectOneByEntitySelective(FormQxSjshSbbJz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormQxSjshSbbJz> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    Page<FormQxSjshSbbJz> pagedSelectByExample(@Param("example") FormQxSjshSbbJzExample example,@Param("page") Page<FormQxSjshSbbJz> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    Page<FormQxSjshSbbJz> pagedSelectByEntity(@Param("record") FormQxSjshSbbJz record,@Param("page") Page<FormQxSjshSbbJz> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjsh_sbb_jz
     *
     * @mbggenerated Tue Jun 21 13:49:55 CST 2016
     */
    List<FormQxSjshSbbJz> SelectByPrimaryKeyList(List<Long> bIdList);
}