package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormRfJgyszhb;
import com.lpcode.modules.blsp.entity.FormRfJgyszhbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormRfJgyszhbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    int countByExample(FormRfJgyszhbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    int deleteByExample(FormRfJgyszhbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    int insert(FormRfJgyszhb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    int insertSelective(FormRfJgyszhb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    List<FormRfJgyszhb> selectByExample(FormRfJgyszhbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    FormRfJgyszhb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormRfJgyszhb record, @Param("example") FormRfJgyszhbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    int updateByExample(@Param("record") FormRfJgyszhb record, @Param("example") FormRfJgyszhbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    int updateByPrimaryKeySelective(FormRfJgyszhb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    int updateByPrimaryKey(FormRfJgyszhb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    List<FormRfJgyszhb> selectByEntitySelective(FormRfJgyszhb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    FormRfJgyszhb selectOneByEntitySelective(FormRfJgyszhb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormRfJgyszhb> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    Page<FormRfJgyszhb> pagedSelectByExample(@Param("example") FormRfJgyszhbExample example, @Param("page") Page<FormRfJgyszhb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    Page<FormRfJgyszhb> pagedSelectByEntity(@Param("record") FormRfJgyszhb record, @Param("page") Page<FormRfJgyszhb> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_rf_jgyszhb
     *
     * @mbggenerated Mon Jul 18 10:32:19 CST 2016
     */
    List<FormRfJgyszhb> SelectByPrimaryKeyList(List<Long> idList);
}