package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.FormQxSjjsPjxx;
import com.lpcode.modules.blsp.entity.FormQxSjjsPjxxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormQxSjjsPjxxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    int countByExample(FormQxSjjsPjxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    int deleteByExample(FormQxSjjsPjxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    int insert(FormQxSjjsPjxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    int insertSelective(FormQxSjjsPjxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    List<FormQxSjjsPjxx> selectByExample(FormQxSjjsPjxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    FormQxSjjsPjxx selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") FormQxSjjsPjxx record, @Param("example") FormQxSjjsPjxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    int updateByExample(@Param("record") FormQxSjjsPjxx record, @Param("example") FormQxSjjsPjxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    int updateByPrimaryKeySelective(FormQxSjjsPjxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    int updateByPrimaryKey(FormQxSjjsPjxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    List<FormQxSjjsPjxx> selectByEntitySelective(FormQxSjjsPjxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    FormQxSjjsPjxx selectOneByEntitySelective(FormQxSjjsPjxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<FormQxSjjsPjxx> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    Page<FormQxSjjsPjxx> pagedSelectByExample(@Param("example") FormQxSjjsPjxxExample example, @Param("page") Page<FormQxSjjsPjxx> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    Page<FormQxSjjsPjxx> pagedSelectByEntity(@Param("record") FormQxSjjsPjxx record, @Param("page") Page<FormQxSjjsPjxx> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_qx_sjjs_pjxx
     *
     * @mbggenerated Mon Jun 27 13:50:55 CST 2016
     */
    List<FormQxSjjsPjxx> SelectByPrimaryKeyList(List<Long> idList);
}