package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.LogOperate;
import com.lpcode.modules.blsp.entity.LogOperateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogOperateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int countByExample(LogOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByExample(LogOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insert(LogOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insertSelective(LogOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<LogOperate> selectByExampleWithBLOBs(LogOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<LogOperate> selectByExample(LogOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    LogOperate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") LogOperate record, @Param("example") LogOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") LogOperate record, @Param("example") LogOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExample(@Param("record") LogOperate record, @Param("example") LogOperateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeySelective(LogOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(LogOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKey(LogOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<LogOperate> selectByEntitySelective(LogOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    LogOperate selectOneByEntitySelective(LogOperate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<LogOperate> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<LogOperate> pagedSelectByExample(@Param("example") LogOperateExample example, @Param("page") Page<LogOperate> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<LogOperate> pagedSelectByEntity(@Param("record") LogOperate record, @Param("page") Page<LogOperate> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_log_operate
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<LogOperate> SelectByPrimaryKeyList(List<String> idList);
}