package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.MessageTpl;
import com.lpcode.modules.blsp.entity.MessageTplExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageTplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int countByExample(MessageTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByExample(MessageTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByPrimaryKey(String tplid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insert(MessageTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insertSelective(MessageTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<MessageTpl> selectByExampleWithBLOBs(MessageTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<MessageTpl> selectByExample(MessageTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    MessageTpl selectByPrimaryKey(String tplid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") MessageTpl record, @Param("example") MessageTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") MessageTpl record, @Param("example") MessageTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExample(@Param("record") MessageTpl record, @Param("example") MessageTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeySelective(MessageTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(MessageTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKey(MessageTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<MessageTpl> selectByEntitySelective(MessageTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    MessageTpl selectOneByEntitySelective(MessageTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<MessageTpl> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<MessageTpl> pagedSelectByExample(@Param("example") MessageTplExample example, @Param("page") Page<MessageTpl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<MessageTpl> pagedSelectByEntity(@Param("record") MessageTpl record, @Param("page") Page<MessageTpl> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_tpl
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<MessageTpl> SelectByPrimaryKeyList(List<String> tplidList);
}