package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.MessageQueue;
import com.lpcode.modules.blsp.entity.MessageQueueExample;
import com.lpcode.modules.blsp.entity.MessageQueueWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int countByExample(MessageQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByExample(MessageQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insert(MessageQueueWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insertSelective(MessageQueueWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<MessageQueueWithBLOBs> selectByExampleWithBLOBs(MessageQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<MessageQueue> selectByExample(MessageQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    MessageQueueWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") MessageQueueWithBLOBs record, @Param("example") MessageQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") MessageQueueWithBLOBs record, @Param("example") MessageQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExample(@Param("record") MessageQueue record, @Param("example") MessageQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeySelective(MessageQueueWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(MessageQueueWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKey(MessageQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<MessageQueue> selectByEntitySelective(MessageQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    MessageQueueWithBLOBs selectOneByEntitySelective(MessageQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<MessageQueue> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<MessageQueue> pagedSelectByExample(@Param("example") MessageQueueExample example, @Param("page") Page<MessageQueue> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<MessageQueue> pagedSelectByEntity(@Param("record") MessageQueue record, @Param("page") Page<MessageQueue> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_message_queue
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<MessageQueue> SelectByPrimaryKeyList(List<String> idList);
}