package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.PrjBusinessAccept;
import com.lpcode.modules.blsp.entity.PrjBusinessAcceptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrjBusinessAcceptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int countByExample(PrjBusinessAcceptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByExample(PrjBusinessAcceptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insert(PrjBusinessAccept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insertSelective(PrjBusinessAccept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjBusinessAccept> selectByExample(PrjBusinessAcceptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjBusinessAccept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") PrjBusinessAccept record, @Param("example") PrjBusinessAcceptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExample(@Param("record") PrjBusinessAccept record, @Param("example") PrjBusinessAcceptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeySelective(PrjBusinessAccept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKey(PrjBusinessAccept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjBusinessAccept> selectByEntitySelective(PrjBusinessAccept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjBusinessAccept selectOneByEntitySelective(PrjBusinessAccept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<PrjBusinessAccept> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjBusinessAccept> pagedSelectByExample(@Param("example") PrjBusinessAcceptExample example, @Param("page") Page<PrjBusinessAccept> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjBusinessAccept> pagedSelectByEntity(@Param("record") PrjBusinessAccept record, @Param("page") Page<PrjBusinessAccept> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_business_accept
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjBusinessAccept> SelectByPrimaryKeyList(List<Long> idList);
}