package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.PrjFetchView;
import com.lpcode.modules.blsp.entity.PrjFetchViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrjFetchViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    int countByExample(PrjFetchViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    int deleteByExample(PrjFetchViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    int insert(PrjFetchView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    int insertSelective(PrjFetchView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    List<PrjFetchView> selectByExample(PrjFetchViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") PrjFetchView record, @Param("example") PrjFetchViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    int updateByExample(@Param("record") PrjFetchView record, @Param("example") PrjFetchViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    List<PrjFetchView> selectByEntitySelective(PrjFetchView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    PrjFetchView selectOneByEntitySelective(PrjFetchView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    @Batch
    int insertSelectiveBatch(List<PrjFetchView> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    Page<PrjFetchView> pagedSelectByExample(@Param("example") PrjFetchViewExample example, @Param("page") Page<PrjFetchView> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    Page<PrjFetchView> pagedSelectByEntity(@Param("record") PrjFetchView record, @Param("page") Page<PrjFetchView> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_fetch_view
     *
     * @mbggenerated Thu May 11 16:54:43 CST 2017
     */
    List<PrjFetchView> SelectByPrimaryKeyList();
}