package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.PrjInstance;
import com.lpcode.modules.blsp.entity.PrjInstanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrjInstanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    int countByExample(PrjInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    int deleteByExample(PrjInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    int insert(PrjInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    int insertSelective(PrjInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    List<PrjInstance> selectByExample(PrjInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    PrjInstance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") PrjInstance record, @Param("example") PrjInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    int updateByExample(@Param("record") PrjInstance record, @Param("example") PrjInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    int updateByPrimaryKeySelective(PrjInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    int updateByPrimaryKey(PrjInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    List<PrjInstance> selectByEntitySelective(PrjInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    PrjInstance selectOneByEntitySelective(PrjInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<PrjInstance> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    Page<PrjInstance> pagedSelectByExample(@Param("example") PrjInstanceExample example, @Param("page") Page<PrjInstance> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    Page<PrjInstance> pagedSelectByEntity(@Param("record") PrjInstance record, @Param("page") Page<PrjInstance> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_instance
     *
     * @mbggenerated Tue Nov 29 16:57:24 CST 2016
     */
    List<PrjInstance> SelectByPrimaryKeyList(List<Long> idList);
}