package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.PrjStageMaterialDefine;
import com.lpcode.modules.blsp.entity.PrjStageMaterialDefineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrjStageMaterialDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int countByExample(PrjStageMaterialDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByExample(PrjStageMaterialDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insert(PrjStageMaterialDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insertSelective(PrjStageMaterialDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStageMaterialDefine> selectByExample(PrjStageMaterialDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjStageMaterialDefine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") PrjStageMaterialDefine record, @Param("example") PrjStageMaterialDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExample(@Param("record") PrjStageMaterialDefine record, @Param("example") PrjStageMaterialDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeySelective(PrjStageMaterialDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKey(PrjStageMaterialDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStageMaterialDefine> selectByEntitySelective(PrjStageMaterialDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjStageMaterialDefine selectOneByEntitySelective(PrjStageMaterialDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<PrjStageMaterialDefine> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjStageMaterialDefine> pagedSelectByExample(@Param("example") PrjStageMaterialDefineExample example, @Param("page") Page<PrjStageMaterialDefine> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjStageMaterialDefine> pagedSelectByEntity(@Param("record") PrjStageMaterialDefine record, @Param("page") Page<PrjStageMaterialDefine> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStageMaterialDefine> SelectByPrimaryKeyList(List<Long> idList);
}