package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.PrjStage;
import com.lpcode.modules.blsp.entity.PrjStageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrjStageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int countByExample(PrjStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByExample(PrjStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insert(PrjStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insertSelective(PrjStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStage> selectByExample(PrjStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjStage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") PrjStage record, @Param("example") PrjStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExample(@Param("record") PrjStage record, @Param("example") PrjStageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeySelective(PrjStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKey(PrjStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStage> selectByEntitySelective(PrjStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjStage selectOneByEntitySelective(PrjStage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<PrjStage> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjStage> pagedSelectByExample(@Param("example") PrjStageExample example, @Param("page") Page<PrjStage> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjStage> pagedSelectByEntity(@Param("record") PrjStage record, @Param("page") Page<PrjStage> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStage> SelectByPrimaryKeyList(List<Long> idList);
}