package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.PrjStageMaterial;
import com.lpcode.modules.blsp.entity.PrjStageMaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrjStageMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int countByExample(PrjStageMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByExample(PrjStageMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insert(PrjStageMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insertSelective(PrjStageMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStageMaterial> selectByExample(PrjStageMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjStageMaterial selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") PrjStageMaterial record, @Param("example") PrjStageMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExample(@Param("record") PrjStageMaterial record, @Param("example") PrjStageMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeySelective(PrjStageMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKey(PrjStageMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStageMaterial> selectByEntitySelective(PrjStageMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjStageMaterial selectOneByEntitySelective(PrjStageMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<PrjStageMaterial> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjStageMaterial> pagedSelectByExample(@Param("example") PrjStageMaterialExample example, @Param("page") Page<PrjStageMaterial> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjStageMaterial> pagedSelectByEntity(@Param("record") PrjStageMaterial record, @Param("page") Page<PrjStageMaterial> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStageMaterial> SelectByPrimaryKeyList(List<Long> idList);
}