package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.PrjStageDefine;
import com.lpcode.modules.blsp.entity.PrjStageDefineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrjStageDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int countByExample(PrjStageDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByExample(PrjStageDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insert(PrjStageDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insertSelective(PrjStageDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStageDefine> selectByExample(PrjStageDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjStageDefine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") PrjStageDefine record, @Param("example") PrjStageDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExample(@Param("record") PrjStageDefine record, @Param("example") PrjStageDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeySelective(PrjStageDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKey(PrjStageDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStageDefine> selectByEntitySelective(PrjStageDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjStageDefine selectOneByEntitySelective(PrjStageDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<PrjStageDefine> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjStageDefine> pagedSelectByExample(@Param("example") PrjStageDefineExample example, @Param("page") Page<PrjStageDefine> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjStageDefine> pagedSelectByEntity(@Param("record") PrjStageDefine record, @Param("page") Page<PrjStageDefine> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_stage_define
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjStageDefine> SelectByPrimaryKeyList(List<Long> idList);
}