package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.PrjTaskMsgRelDefine;
import com.lpcode.modules.blsp.entity.PrjTaskMsgRelDefineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrjTaskMsgRelDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    int countByExample(PrjTaskMsgRelDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    int deleteByExample(PrjTaskMsgRelDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    int insert(PrjTaskMsgRelDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    int insertSelective(PrjTaskMsgRelDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    List<PrjTaskMsgRelDefine> selectByExample(PrjTaskMsgRelDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    PrjTaskMsgRelDefine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") PrjTaskMsgRelDefine record, @Param("example") PrjTaskMsgRelDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    int updateByExample(@Param("record") PrjTaskMsgRelDefine record, @Param("example") PrjTaskMsgRelDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    int updateByPrimaryKeySelective(PrjTaskMsgRelDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    int updateByPrimaryKey(PrjTaskMsgRelDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    List<PrjTaskMsgRelDefine> selectByEntitySelective(PrjTaskMsgRelDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    PrjTaskMsgRelDefine selectOneByEntitySelective(PrjTaskMsgRelDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<PrjTaskMsgRelDefine> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    Page<PrjTaskMsgRelDefine> pagedSelectByExample(@Param("example") PrjTaskMsgRelDefineExample example, @Param("page") Page<PrjTaskMsgRelDefine> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    Page<PrjTaskMsgRelDefine> pagedSelectByEntity(@Param("record") PrjTaskMsgRelDefine record, @Param("page") Page<PrjTaskMsgRelDefine> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_msg_rel_define
     *
     * @mbggenerated Tue Jun 21 17:13:02 CST 2016
     */
    List<PrjTaskMsgRelDefine> SelectByPrimaryKeyList(List<Long> idList);
}