package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.PrjTaskRejectMaterial;
import com.lpcode.modules.blsp.entity.PrjTaskRejectMaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrjTaskRejectMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int countByExample(PrjTaskRejectMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByExample(PrjTaskRejectMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insert(PrjTaskRejectMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int insertSelective(PrjTaskRejectMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjTaskRejectMaterial> selectByExample(PrjTaskRejectMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjTaskRejectMaterial selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") PrjTaskRejectMaterial record, @Param("example") PrjTaskRejectMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByExample(@Param("record") PrjTaskRejectMaterial record, @Param("example") PrjTaskRejectMaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKeySelective(PrjTaskRejectMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    int updateByPrimaryKey(PrjTaskRejectMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjTaskRejectMaterial> selectByEntitySelective(PrjTaskRejectMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    PrjTaskRejectMaterial selectOneByEntitySelective(PrjTaskRejectMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<PrjTaskRejectMaterial> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjTaskRejectMaterial> pagedSelectByExample(@Param("example") PrjTaskRejectMaterialExample example, @Param("page") Page<PrjTaskRejectMaterial> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    Page<PrjTaskRejectMaterial> pagedSelectByEntity(@Param("record") PrjTaskRejectMaterial record, @Param("page") Page<PrjTaskRejectMaterial> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prj_task_reject_material
     *
     * @mbggenerated Mon Jun 20 17:28:14 CST 2016
     */
    List<PrjTaskRejectMaterial> SelectByPrimaryKeyList(List<Long> idList);
}