package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.ServiceBasicinfoPushLog;
import com.lpcode.modules.blsp.entity.ServiceBasicinfoPushLogExample;
import com.lpcode.modules.blsp.entity.ServiceBasicinfoPushLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceBasicinfoPushLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int countByExample(ServiceBasicinfoPushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int deleteByExample(ServiceBasicinfoPushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int insert(ServiceBasicinfoPushLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int insertSelective(ServiceBasicinfoPushLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    List<ServiceBasicinfoPushLogWithBLOBs> selectByExampleWithBLOBs(ServiceBasicinfoPushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    List<ServiceBasicinfoPushLog> selectByExample(ServiceBasicinfoPushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    ServiceBasicinfoPushLogWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int updateByExampleSelective(@Param("record") ServiceBasicinfoPushLogWithBLOBs record, @Param("example") ServiceBasicinfoPushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ServiceBasicinfoPushLogWithBLOBs record, @Param("example") ServiceBasicinfoPushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int updateByExample(@Param("record") ServiceBasicinfoPushLog record, @Param("example") ServiceBasicinfoPushLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int updateByPrimaryKeySelective(ServiceBasicinfoPushLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ServiceBasicinfoPushLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    int updateByPrimaryKey(ServiceBasicinfoPushLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    List<ServiceBasicinfoPushLog> selectByEntitySelective(ServiceBasicinfoPushLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    ServiceBasicinfoPushLogWithBLOBs selectOneByEntitySelective(ServiceBasicinfoPushLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<ServiceBasicinfoPushLog> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    Page<ServiceBasicinfoPushLog> pagedSelectByExample(@Param("example") ServiceBasicinfoPushLogExample example, @Param("page") Page<ServiceBasicinfoPushLog> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    Page<ServiceBasicinfoPushLog> pagedSelectByEntity(@Param("record") ServiceBasicinfoPushLog record, @Param("page") Page<ServiceBasicinfoPushLog> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_basicinfo_push_log
     *
     * @mbggenerated Thu Dec 08 18:41:00 CST 2016
     */
    List<ServiceBasicinfoPushLog> SelectByPrimaryKeyList(List<String> idList);
}