package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.ServiceSbQueue;
import com.lpcode.modules.blsp.entity.ServiceSbQueueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceSbQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    int countByExample(ServiceSbQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    int deleteByExample(ServiceSbQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    int insert(ServiceSbQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    int insertSelective(ServiceSbQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    List<ServiceSbQueue> selectByExample(ServiceSbQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    ServiceSbQueue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") ServiceSbQueue record, @Param("example") ServiceSbQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    int updateByExample(@Param("record") ServiceSbQueue record, @Param("example") ServiceSbQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    int updateByPrimaryKeySelective(ServiceSbQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    int updateByPrimaryKey(ServiceSbQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    List<ServiceSbQueue> selectByEntitySelective(ServiceSbQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    ServiceSbQueue selectOneByEntitySelective(ServiceSbQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    @Batch
    int insertSelectiveBatch(List<ServiceSbQueue> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    Page<ServiceSbQueue> pagedSelectByExample(@Param("example") ServiceSbQueueExample example, @Param("page") Page<ServiceSbQueue> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    Page<ServiceSbQueue> pagedSelectByEntity(@Param("record") ServiceSbQueue record, @Param("page") Page<ServiceSbQueue> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_queue
     *
     * @mbggenerated Thu May 18 18:08:27 CST 2017
     */
    List<ServiceSbQueue> SelectByPrimaryKeyList(List<String> idList);
}