package com.lpcode.modules.blsp.mapper;

import com.framework.core.base.page.Page;
import com.framework.mybatis.annotation.Batch;
import com.lpcode.modules.blsp.entity.ServiceSbLog;
import com.lpcode.modules.blsp.entity.ServiceSbLogExample;
import com.lpcode.modules.blsp.entity.ServiceSbLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceSbLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int countByExample(ServiceSbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int deleteByExample(ServiceSbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int insert(ServiceSbLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int insertSelective(ServiceSbLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    List<ServiceSbLogWithBLOBs> selectByExampleWithBLOBs(ServiceSbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    List<ServiceSbLog> selectByExample(ServiceSbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    ServiceSbLogWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") ServiceSbLogWithBLOBs record, @Param("example") ServiceSbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ServiceSbLogWithBLOBs record, @Param("example") ServiceSbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int updateByExample(@Param("record") ServiceSbLog record, @Param("example") ServiceSbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int updateByPrimaryKeySelective(ServiceSbLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ServiceSbLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    int updateByPrimaryKey(ServiceSbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    List<ServiceSbLog> selectByEntitySelective(ServiceSbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    ServiceSbLogWithBLOBs selectOneByEntitySelective(ServiceSbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    @Batch
    int insertSelectiveBatch(List<ServiceSbLog> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    Page<ServiceSbLog> pagedSelectByExample(@Param("example") ServiceSbLogExample example, @Param("page") Page<ServiceSbLog> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    Page<ServiceSbLog> pagedSelectByEntity(@Param("record") ServiceSbLog record, @Param("page") Page<ServiceSbLog> page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_sb_log
     *
     * @mbggenerated Wed Dec 14 17:26:34 CST 2016
     */
    List<ServiceSbLog> SelectByPrimaryKeyList(List<String> idList);
}